module Sentdm
  module Models
    module Brands
      type api_response_tcr_campaign_with_use_cases =
        {
          data: Sentdm::Brands::TcrCampaignWithUseCases?,
          error: Sentdm::APIError?,
          meta: Sentdm::APIMeta,
          success: bool
        }

      class APIResponseTcrCampaignWithUseCases < Sentdm::Internal::Type::BaseModel
        attr_accessor data: Sentdm::Brands::TcrCampaignWithUseCases?

        attr_accessor error: Sentdm::APIError?

        attr_reader meta: Sentdm::APIMeta?

        def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (
          ?data: Sentdm::Brands::TcrCampaignWithUseCases?,
          ?error: Sentdm::APIError?,
          ?meta: Sentdm::APIMeta,
          ?success: bool
        ) -> void

        def to_hash: -> {
          data: Sentdm::Brands::TcrCampaignWithUseCases?,
          error: Sentdm::APIError?,
          meta: Sentdm::APIMeta,
          success: bool
        }
      end
    end
  end
end
