module Sentdm
  module Models
    module Brands
      type messaging_use_case_us =
        :MARKETING
        | :ACCOUNT_NOTIFICATION
        | :CUSTOMER_CARE
        | :FRAUD_ALERT
        | :TWO_FA
        | :DELIVERY_NOTIFICATION
        | :SECURITY_ALERT
        | :M2M
        | :MIXED
        | :HIGHER_EDUCATION
        | :POLLING_VOTING
        | :PUBLIC_SERVICE_ANNOUNCEMENT
        | :LOW_VOLUME

      module MessagingUseCaseUs
        extend Sentdm::Internal::Type::Enum

        MARKETING: :MARKETING
        ACCOUNT_NOTIFICATION: :ACCOUNT_NOTIFICATION
        CUSTOMER_CARE: :CUSTOMER_CARE
        FRAUD_ALERT: :FRAUD_ALERT
        TWO_FA: :TWO_FA
        DELIVERY_NOTIFICATION: :DELIVERY_NOTIFICATION
        SECURITY_ALERT: :SECURITY_ALERT
        M2_M: :M2M
        MIXED: :MIXED
        HIGHER_EDUCATION: :HIGHER_EDUCATION
        POLLING_VOTING: :POLLING_VOTING
        PUBLIC_SERVICE_ANNOUNCEMENT: :PUBLIC_SERVICE_ANNOUNCEMENT
        LOW_VOLUME: :LOW_VOLUME

        def self?.values: -> ::Array[Sentdm::Models::Brands::messaging_use_case_us]
      end
    end
  end
end
