module Sentdm
  module Models
    module Profiles
      type campaign_list_params =
        { profile_id: String, x_profile_id: String }
        & Sentdm::Internal::Type::request_parameters

      class CampaignListParams < Sentdm::Internal::Type::BaseModel
        extend Sentdm::Internal::Type::RequestParameters::Converter
        include Sentdm::Internal::Type::RequestParameters

        attr_accessor profile_id: String

        attr_reader x_profile_id: String?

        def x_profile_id=: (String) -> String

        def initialize: (
          profile_id: String,
          ?x_profile_id: String,
          ?request_options: Sentdm::request_opts
        ) -> void

        def to_hash: -> {
          profile_id: String,
          x_profile_id: String,
          request_options: Sentdm::RequestOptions
        }
      end
    end
  end
end
