module Sentdm
  module Models
    module Profiles
      type campaign_use_case =
        {
          id: String,
          campaign_id: String,
          created_at: Time,
          customer_id: String,
          messaging_use_case_us: Sentdm::Models::Profiles::messaging_use_case_us,
          sample_messages: ::Array[String],
          updated_at: Time?
        }

      class CampaignUseCase < Sentdm::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader campaign_id: String?

        def campaign_id=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader customer_id: String?

        def customer_id=: (String) -> String

        attr_reader messaging_use_case_us: Sentdm::Models::Profiles::messaging_use_case_us?

        def messaging_use_case_us=: (
          Sentdm::Models::Profiles::messaging_use_case_us
        ) -> Sentdm::Models::Profiles::messaging_use_case_us

        attr_reader sample_messages: ::Array[String]?

        def sample_messages=: (::Array[String]) -> ::Array[String]

        attr_accessor updated_at: Time?

        def initialize: (
          ?id: String,
          ?campaign_id: String,
          ?created_at: Time,
          ?customer_id: String,
          ?messaging_use_case_us: Sentdm::Models::Profiles::messaging_use_case_us,
          ?sample_messages: ::Array[String],
          ?updated_at: Time?
        ) -> void

        def to_hash: -> {
          id: String,
          campaign_id: String,
          created_at: Time,
          customer_id: String,
          messaging_use_case_us: Sentdm::Models::Profiles::messaging_use_case_us,
          sample_messages: ::Array[String],
          updated_at: Time?
        }
      end
    end
  end
end
