module Sentdm
  module Resources
    class Contacts
      def create: (
        ?phone_number: String,
        ?sandbox: bool,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfContact

      def retrieve: (
        String id,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfContact

      def update: (
        String id,
        ?channel_consent: ::Hash[Symbol, String]?,
        ?default_channel: String?,
        ?opt_out: bool?,
        ?sandbox: bool,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfContact

      def list: (
        page: Integer,
        page_size: Integer,
        ?channel: String?,
        ?phone: String?,
        ?search: String?,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::ContactListResponse

      def delete: (
        String id,
        ?sandbox: bool,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> nil

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
