module Sentdm
  module Resources
    class Me
      def retrieve: (
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::MeRetrieveResponse

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
