module Sentdm
  module Resources
    class Messages
      def retrieve_activities: (
        String id,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::MessageRetrieveActivitiesResponse

      def retrieve_status: (
        String id,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::MessageRetrieveStatusResponse

      def send_: (
        ?channel: ::Array[String]?,
        ?sandbox: bool,
        ?template: Sentdm::MessageSendParams::Template,
        ?to: ::Array[String],
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::MessageSendResponse

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
