module Sentdm
  module Resources
    class Numbers
      def lookup: (
        String phone_number,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::NumberLookupResponse

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
