module Sentdm
  module Resources
    class Templates
      def create: (
        definition: Sentdm::TemplateDefinition,
        ?category: String?,
        ?language: String?,
        ?submit_for_review: bool,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::TemplateResponseV2

      def retrieve: (
        String id,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::TemplateResponseV2

      def list: (
        page: Integer,
        page_size: Integer,
        ?category: String?,
        ?search: String?,
        ?status: String?,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::TemplateListResponse

      def delete: (String id, ?request_options: Sentdm::request_opts) -> nil

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
