module Sentdm
  module Resources
    class Templates
      def create: (
        ?category: String?,
        ?creation_source: String?,
        ?definition: Sentdm::TemplateDefinition,
        ?language: String?,
        ?submit_for_review: bool,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseTemplate

      def retrieve: (
        String id,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseTemplate

      def update: (
        String id,
        ?category: String?,
        ?definition: Sentdm::TemplateDefinition?,
        ?language: String?,
        ?name: String?,
        ?submit_for_review: bool,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseTemplate

      def list: (
        page: Integer,
        page_size: Integer,
        ?category: String?,
        ?search: String?,
        ?status: String?,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::TemplateListResponse

      def delete: (
        String id,
        ?delete_from_meta: bool?,
        ?test_mode: bool,
        ?request_options: Sentdm::request_opts
      ) -> nil

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
