module Sentdm
  module Resources
    class Users
      def retrieve: (
        String user_id,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfUser

      def list: (
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::Models::UserListResponse

      def invite: (
        ?email: String,
        ?name: String,
        ?role: String,
        ?sandbox: bool,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfUser

      def remove: (
        String user_id,
        ?sandbox: bool,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> nil

      def update_role: (
        String user_id,
        ?role: String,
        ?sandbox: bool,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> Sentdm::APIResponseOfUser

      def initialize: (client: Sentdm::Client) -> void
    end
  end
end
