module SentDm
  class Client < SentDm::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader admin_auth_scheme: String

    attr_reader customer_auth_scheme: String

    attr_reader templates: SentDm::Resources::Templates

    attr_reader contacts: SentDm::Resources::Contacts

    attr_reader messages: SentDm::Resources::Messages

    attr_reader number_lookup: SentDm::Resources::NumberLookup

    attr_reader organizations: SentDm::Resources::Organizations

    private def auth_headers: -> ::Hash[String, String]

    private def admin_authentication_scheme: -> ::Hash[String, String]

    private def customer_authentication_scheme: -> ::Hash[String, String]

    def initialize: (
      ?admin_auth_scheme: String?,
      ?customer_auth_scheme: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
