module SentDm
  module Models
    module Brands
      type base_dto = { id: String, created_at: Time, updated_at: Time? }

      class BaseDto < SentDm::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_accessor updated_at: Time?

        def initialize: (
          ?id: String,
          ?created_at: Time,
          ?updated_at: Time?
        ) -> void

        def to_hash: -> { id: String, created_at: Time, updated_at: Time? }
      end
    end
  end
end
