module SentDm
  module Models
    module Brands
      type campaign_list_response =
        {
          data: ::Array[SentDm::Brands::TcrCampaignWithUseCases]?,
          error: SentDm::APIError?,
          meta: SentDm::APIMeta,
          success: bool
        }

      class CampaignListResponse < SentDm::Internal::Type::BaseModel
        attr_accessor data: ::Array[SentDm::Brands::TcrCampaignWithUseCases]?

        attr_accessor error: SentDm::APIError?

        attr_reader meta: SentDm::APIMeta?

        def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (
          ?data: ::Array[SentDm::Brands::TcrCampaignWithUseCases]?,
          ?error: SentDm::APIError?,
          ?meta: SentDm::APIMeta,
          ?success: bool
        ) -> void

        def to_hash: -> {
          data: ::Array[SentDm::Brands::TcrCampaignWithUseCases]?,
          error: SentDm::APIError?,
          meta: SentDm::APIMeta,
          success: bool
        }
      end
    end
  end
end
