module Sentdm
  module Resources
    class Brands
      class Campaigns
        def create: (
          String brand_id,
          campaign: Sentdm::Brands::CampaignData,
          ?test_mode: bool,
          ?idempotency_key: String,
          ?request_options: Sentdm::request_opts
        ) -> Sentdm::Brands::APIResponseTcrCampaignWithUseCases

        def update: (
          String campaign_id,
          brand_id: String,
          campaign: Sentdm::Brands::CampaignData,
          ?test_mode: bool,
          ?idempotency_key: String,
          ?request_options: Sentdm::request_opts
        ) -> Sentdm::Brands::APIResponseTcrCampaignWithUseCases

        def list: (
          String brand_id,
          ?request_options: Sentdm::request_opts
        ) -> Sentdm::Models::Brands::CampaignListResponse

        def delete: (
          String campaign_id,
          brand_id: String,
          body: Sentdm::Brands::CampaignDeleteParams::Body,
          ?request_options: Sentdm::request_opts
        ) -> nil

        def initialize: (client: Sentdm::Client) -> void
      end
    end
  end
end
