module SentDm
  module Resources
    class Messages
      def retrieve: (
        String id,
        ?request_options: SentDm::request_opts
      ) -> SentDm::Models::MessageRetrieveResponse

      def send_quick_message: (
        custom_message: String,
        phone_number: String,
        ?request_options: SentDm::request_opts
      ) -> nil

      def send_to_contact: (
        contact_id: String,
        template_id: String,
        ?template_variables: ::Hash[Symbol, String]?,
        ?request_options: SentDm::request_opts
      ) -> nil

      def send_to_phone: (
        phone_number: String,
        template_id: String,
        ?template_variables: ::Hash[Symbol, String]?,
        ?request_options: SentDm::request_opts
      ) -> nil

      def initialize: (client: SentDm::Client) -> void
    end
  end
end
