module SentDm
  module Resources
    class NumberLookup
      def retrieve: (
        phone_number: String,
        x_api_key: String,
        x_sender_id: String,
        ?request_options: SentDm::request_opts
      ) -> SentDm::Models::NumberLookupRetrieveResponse

      def initialize: (client: SentDm::Client) -> void
    end
  end
end
