module SentDm
  module Resources
    class Organizations
      attr_reader users: SentDm::Resources::Organizations::Users

      def list: (
        ?request_options: SentDm::request_opts
      ) -> SentDm::Models::OrganizationListResponse

      def retrieve_profiles: (
        String org_id,
        x_api_key: String,
        x_sender_id: String,
        ?request_options: SentDm::request_opts
      ) -> SentDm::Models::OrganizationRetrieveProfilesResponse

      def initialize: (client: SentDm::Client) -> void
    end
  end
end
