# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "sent_dm/version"
require_relative "sent_dm/internal/util"
require_relative "sent_dm/internal/type/converter"
require_relative "sent_dm/internal/type/unknown"
require_relative "sent_dm/internal/type/boolean"
require_relative "sent_dm/internal/type/file_input"
require_relative "sent_dm/internal/type/enum"
require_relative "sent_dm/internal/type/union"
require_relative "sent_dm/internal/type/array_of"
require_relative "sent_dm/internal/type/hash_of"
require_relative "sent_dm/internal/type/base_model"
require_relative "sent_dm/internal/type/base_page"
require_relative "sent_dm/internal/type/request_parameters"
require_relative "sent_dm/internal"
require_relative "sent_dm/request_options"
require_relative "sent_dm/file_part"
require_relative "sent_dm/errors"
require_relative "sent_dm/internal/transport/base_client"
require_relative "sent_dm/internal/transport/pooled_net_requester"
require_relative "sent_dm/client"
require_relative "sent_dm/models/contact_list_item"
require_relative "sent_dm/models/contact_list_params"
require_relative "sent_dm/models/contact_list_response"
require_relative "sent_dm/models/contact_retrieve_by_phone_params"
require_relative "sent_dm/models/contact_retrieve_id_params"
require_relative "sent_dm/models/message_retrieve_params"
require_relative "sent_dm/models/message_retrieve_response"
require_relative "sent_dm/models/message_send_quick_message_params"
require_relative "sent_dm/models/message_send_to_contact_params"
require_relative "sent_dm/models/message_send_to_phone_params"
require_relative "sent_dm/models/number_lookup_retrieve_params"
require_relative "sent_dm/models/number_lookup_retrieve_response"
require_relative "sent_dm/models/organization_list_params"
require_relative "sent_dm/models/organization_list_response"
require_relative "sent_dm/models/organization_retrieve_profiles_params"
require_relative "sent_dm/models/organization_retrieve_profiles_response"
require_relative "sent_dm/models/organizations/customer_user"
require_relative "sent_dm/models/organizations/user_delete_params"
require_relative "sent_dm/models/organizations/user_invite_params"
require_relative "sent_dm/models/organizations/user_list_params"
require_relative "sent_dm/models/organizations/user_list_response"
require_relative "sent_dm/models/organizations/user_retrieve_params"
require_relative "sent_dm/models/organizations/user_update_role_params"
require_relative "sent_dm/models/profile_summary"
require_relative "sent_dm/models/template_body_content"
require_relative "sent_dm/models/template_create_params"
require_relative "sent_dm/models/template_definition"
require_relative "sent_dm/models/template_delete_params"
require_relative "sent_dm/models/template_list_params"
require_relative "sent_dm/models/template_list_response"
require_relative "sent_dm/models/template_response"
require_relative "sent_dm/models/template_retrieve_params"
require_relative "sent_dm/models/template_variable"
require_relative "sent_dm/models"
require_relative "sent_dm/resources/contacts"
require_relative "sent_dm/resources/messages"
require_relative "sent_dm/resources/number_lookup"
require_relative "sent_dm/resources/organizations"
require_relative "sent_dm/resources/organizations/users"
require_relative "sent_dm/resources/templates"
