# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "sent_dm/version"
require_relative "sent_dm/internal/util"
require_relative "sent_dm/internal/type/converter"
require_relative "sent_dm/internal/type/unknown"
require_relative "sent_dm/internal/type/boolean"
require_relative "sent_dm/internal/type/file_input"
require_relative "sent_dm/internal/type/enum"
require_relative "sent_dm/internal/type/union"
require_relative "sent_dm/internal/type/array_of"
require_relative "sent_dm/internal/type/hash_of"
require_relative "sent_dm/internal/type/base_model"
require_relative "sent_dm/internal/type/base_page"
require_relative "sent_dm/internal/type/request_parameters"
require_relative "sent_dm/internal"
require_relative "sent_dm/request_options"
require_relative "sent_dm/file_part"
require_relative "sent_dm/errors"
require_relative "sent_dm/internal/transport/base_client"
require_relative "sent_dm/internal/transport/pooled_net_requester"
require_relative "sent_dm/client"
require_relative "sent_dm/models/mutation_request"
require_relative "sent_dm/models/brands/base_dto"
require_relative "sent_dm/models/api_error"
require_relative "sent_dm/models/api_meta"
require_relative "sent_dm/models/api_response_brand_with_kyc"
require_relative "sent_dm/models/api_response_contact"
require_relative "sent_dm/models/api_response_of_profile_detail"
require_relative "sent_dm/models/api_response_of_user"
require_relative "sent_dm/models/api_response_template"
require_relative "sent_dm/models/api_response_webhook"
require_relative "sent_dm/models/brand_create_params"
require_relative "sent_dm/models/brand_data"
require_relative "sent_dm/models/brand_delete_params"
require_relative "sent_dm/models/brand_list_params"
require_relative "sent_dm/models/brand_list_response"
require_relative "sent_dm/models/brands/api_response_tcr_campaign_with_use_cases"
require_relative "sent_dm/models/brands/campaign_create_params"
require_relative "sent_dm/models/brands/campaign_data"
require_relative "sent_dm/models/brands/campaign_delete_params"
require_relative "sent_dm/models/brands/campaign_list_params"
require_relative "sent_dm/models/brands/campaign_list_response"
require_relative "sent_dm/models/brands/campaign_update_params"
require_relative "sent_dm/models/brands/messaging_use_case_us"
require_relative "sent_dm/models/brands/tcr_campaign_with_use_cases"
require_relative "sent_dm/models/brand_update_params"
require_relative "sent_dm/models/brand_with_kyc"
require_relative "sent_dm/models/contact"
require_relative "sent_dm/models/contact_create_params"
require_relative "sent_dm/models/contact_delete_params"
require_relative "sent_dm/models/contact_list_params"
require_relative "sent_dm/models/contact_list_response"
require_relative "sent_dm/models/contact_retrieve_params"
require_relative "sent_dm/models/contact_update_params"
require_relative "sent_dm/models/destination_country"
require_relative "sent_dm/models/lookup_retrieve_phone_info_params"
require_relative "sent_dm/models/lookup_retrieve_phone_info_response"
require_relative "sent_dm/models/me_retrieve_params"
require_relative "sent_dm/models/me_retrieve_response"
require_relative "sent_dm/models/message_retrieve_activities_params"
require_relative "sent_dm/models/message_retrieve_activities_response"
require_relative "sent_dm/models/message_retrieve_status_params"
require_relative "sent_dm/models/message_retrieve_status_response"
require_relative "sent_dm/models/message_send_params"
require_relative "sent_dm/models/message_send_response"
require_relative "sent_dm/models/pagination_meta"
require_relative "sent_dm/models/profile_complete_params"
require_relative "sent_dm/models/profile_complete_response"
require_relative "sent_dm/models/profile_create_params"
require_relative "sent_dm/models/profile_delete_params"
require_relative "sent_dm/models/profile_detail"
require_relative "sent_dm/models/profile_list_params"
require_relative "sent_dm/models/profile_list_response"
require_relative "sent_dm/models/profile_retrieve_params"
require_relative "sent_dm/models/profile_settings"
require_relative "sent_dm/models/profile_update_params"
require_relative "sent_dm/models/tcr_brand_relationship"
require_relative "sent_dm/models/tcr_vertical"
require_relative "sent_dm/models/template"
require_relative "sent_dm/models/template_body_content"
require_relative "sent_dm/models/template_create_params"
require_relative "sent_dm/models/template_definition"
require_relative "sent_dm/models/template_delete_params"
require_relative "sent_dm/models/template_list_params"
require_relative "sent_dm/models/template_list_response"
require_relative "sent_dm/models/template_retrieve_params"
require_relative "sent_dm/models/template_update_params"
require_relative "sent_dm/models/template_variable"
require_relative "sent_dm/models/user_invite_params"
require_relative "sent_dm/models/user_list_params"
require_relative "sent_dm/models/user_list_response"
require_relative "sent_dm/models/user_remove_params"
require_relative "sent_dm/models/user_response"
require_relative "sent_dm/models/user_retrieve_params"
require_relative "sent_dm/models/user_update_role_params"
require_relative "sent_dm/models/webhook_create_params"
require_relative "sent_dm/models/webhook_delete_params"
require_relative "sent_dm/models/webhook_list_events_params"
require_relative "sent_dm/models/webhook_list_events_response"
require_relative "sent_dm/models/webhook_list_event_types_params"
require_relative "sent_dm/models/webhook_list_event_types_response"
require_relative "sent_dm/models/webhook_list_params"
require_relative "sent_dm/models/webhook_list_response"
require_relative "sent_dm/models/webhook_response"
require_relative "sent_dm/models/webhook_retrieve_params"
require_relative "sent_dm/models/webhook_rotate_secret_params"
require_relative "sent_dm/models/webhook_rotate_secret_response"
require_relative "sent_dm/models/webhook_test_params"
require_relative "sent_dm/models/webhook_test_response"
require_relative "sent_dm/models/webhook_toggle_status_params"
require_relative "sent_dm/models/webhook_update_params"
require_relative "sent_dm/models"
require_relative "sent_dm/resources/brands"
require_relative "sent_dm/resources/brands/campaigns"
require_relative "sent_dm/resources/contacts"
require_relative "sent_dm/resources/lookup"
require_relative "sent_dm/resources/me"
require_relative "sent_dm/resources/messages"
require_relative "sent_dm/resources/profiles"
require_relative "sent_dm/resources/templates"
require_relative "sent_dm/resources/users"
require_relative "sent_dm/resources/webhooks"
