module SentDm
  module Models
    type api_error =
      {
        code: String,
        details: ::Hash[Symbol, ::Array[String]]?,
        doc_url: String?,
        message: String
      }

    class APIError < SentDm::Internal::Type::BaseModel
      attr_reader code: String?

      def code=: (String) -> String

      attr_accessor details: ::Hash[Symbol, ::Array[String]]?

      attr_accessor doc_url: String?

      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (
        ?code: String,
        ?details: ::Hash[Symbol, ::Array[String]]?,
        ?doc_url: String?,
        ?message: String
      ) -> void

      def to_hash: -> {
        code: String,
        details: ::Hash[Symbol, ::Array[String]]?,
        doc_url: String?,
        message: String
      }
    end
  end
end
