module SentDm
  module Models
    type brand_create_params =
      { brand: SentDm::BrandData, test_mode: bool, idempotency_key: String }
      & SentDm::Internal::Type::request_parameters

    class BrandCreateParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor brand: SentDm::BrandData

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        brand: SentDm::BrandData,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        brand: SentDm::BrandData,
        test_mode: bool,
        idempotency_key: String,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
