module SentDm
  module Models
    type brand_with_kyc =
      {
        id: String,
        brand_relationship: SentDm::Models::tcr_brand_relationship?,
        business_legal_name: String?,
        business_name: String?,
        business_role: String?,
        business_url: String?,
        city: String?,
        contact_email: String?,
        contact_name: String,
        contact_phone: String?,
        contact_phone_country_code: String?,
        country: String?,
        country_of_registration: String?,
        created_at: Time,
        csp_id: String?,
        destination_countries: ::Array[SentDm::DestinationCountry],
        entity_type: String?,
        expected_messaging_volume: String?,
        identity_status: SentDm::Models::BrandWithKYC::identity_status?,
        is_inherited: bool,
        is_tcr_application: bool,
        notes: String?,
        phone_number_prefix: String?,
        postal_code: String?,
        primary_use_case: String?,
        state: String?,
        status: SentDm::Models::BrandWithKYC::status?,
        street: String?,
        submitted_at: Time?,
        submitted_to_tcr: bool,
        tax_id: String?,
        tax_id_type: String?,
        tcr_brand_id: String?,
        universal_ein: String?,
        updated_at: Time?,
        vertical: SentDm::Models::tcr_vertical?
      }

    class BrandWithKYC < SentDm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_accessor brand_relationship: SentDm::Models::tcr_brand_relationship?

      attr_accessor business_legal_name: String?

      attr_accessor business_name: String?

      attr_accessor business_role: String?

      attr_accessor business_url: String?

      attr_accessor city: String?

      attr_accessor contact_email: String?

      attr_reader contact_name: String?

      def contact_name=: (String) -> String

      attr_accessor contact_phone: String?

      attr_accessor contact_phone_country_code: String?

      attr_accessor country: String?

      attr_accessor country_of_registration: String?

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_accessor csp_id: String?

      attr_reader destination_countries: ::Array[SentDm::DestinationCountry]?

      def destination_countries=: (
        ::Array[SentDm::DestinationCountry]
      ) -> ::Array[SentDm::DestinationCountry]

      attr_accessor entity_type: String?

      attr_accessor expected_messaging_volume: String?

      attr_accessor identity_status: SentDm::Models::BrandWithKYC::identity_status?

      attr_reader is_inherited: bool?

      def is_inherited=: (bool) -> bool

      attr_reader is_tcr_application: bool?

      def is_tcr_application=: (bool) -> bool

      attr_accessor notes: String?

      attr_accessor phone_number_prefix: String?

      attr_accessor postal_code: String?

      attr_accessor primary_use_case: String?

      attr_accessor state: String?

      attr_accessor status: SentDm::Models::BrandWithKYC::status?

      attr_accessor street: String?

      attr_accessor submitted_at: Time?

      attr_reader submitted_to_tcr: bool?

      def submitted_to_tcr=: (bool) -> bool

      attr_accessor tax_id: String?

      attr_accessor tax_id_type: String?

      attr_accessor tcr_brand_id: String?

      attr_accessor universal_ein: String?

      attr_accessor updated_at: Time?

      attr_accessor vertical: SentDm::Models::tcr_vertical?

      def initialize: (
        ?id: String,
        ?brand_relationship: SentDm::Models::tcr_brand_relationship?,
        ?business_legal_name: String?,
        ?business_name: String?,
        ?business_role: String?,
        ?business_url: String?,
        ?city: String?,
        ?contact_email: String?,
        ?contact_name: String,
        ?contact_phone: String?,
        ?contact_phone_country_code: String?,
        ?country: String?,
        ?country_of_registration: String?,
        ?created_at: Time,
        ?csp_id: String?,
        ?destination_countries: ::Array[SentDm::DestinationCountry],
        ?entity_type: String?,
        ?expected_messaging_volume: String?,
        ?identity_status: SentDm::Models::BrandWithKYC::identity_status?,
        ?is_inherited: bool,
        ?is_tcr_application: bool,
        ?notes: String?,
        ?phone_number_prefix: String?,
        ?postal_code: String?,
        ?primary_use_case: String?,
        ?state: String?,
        ?status: SentDm::Models::BrandWithKYC::status?,
        ?street: String?,
        ?submitted_at: Time?,
        ?submitted_to_tcr: bool,
        ?tax_id: String?,
        ?tax_id_type: String?,
        ?tcr_brand_id: String?,
        ?universal_ein: String?,
        ?updated_at: Time?,
        ?vertical: SentDm::Models::tcr_vertical?
      ) -> void

      def to_hash: -> {
        id: String,
        brand_relationship: SentDm::Models::tcr_brand_relationship?,
        business_legal_name: String?,
        business_name: String?,
        business_role: String?,
        business_url: String?,
        city: String?,
        contact_email: String?,
        contact_name: String,
        contact_phone: String?,
        contact_phone_country_code: String?,
        country: String?,
        country_of_registration: String?,
        created_at: Time,
        csp_id: String?,
        destination_countries: ::Array[SentDm::DestinationCountry],
        entity_type: String?,
        expected_messaging_volume: String?,
        identity_status: SentDm::Models::BrandWithKYC::identity_status?,
        is_inherited: bool,
        is_tcr_application: bool,
        notes: String?,
        phone_number_prefix: String?,
        postal_code: String?,
        primary_use_case: String?,
        state: String?,
        status: SentDm::Models::BrandWithKYC::status?,
        street: String?,
        submitted_at: Time?,
        submitted_to_tcr: bool,
        tax_id: String?,
        tax_id_type: String?,
        tcr_brand_id: String?,
        universal_ein: String?,
        updated_at: Time?,
        vertical: SentDm::Models::tcr_vertical?
      }

      type identity_status =
        :SELF_DECLARED | :UNVERIFIED | :VERIFIED | :VETTED_VERIFIED

      module IdentityStatus
        extend SentDm::Internal::Type::Enum

        SELF_DECLARED: :SELF_DECLARED
        UNVERIFIED: :UNVERIFIED
        VERIFIED: :VERIFIED
        VETTED_VERIFIED: :VETTED_VERIFIED

        def self?.values: -> ::Array[SentDm::Models::BrandWithKYC::identity_status]
      end

      type status = :ACTIVE | :INACTIVE | :SUSPENDED

      module Status
        extend SentDm::Internal::Type::Enum

        ACTIVE: :ACTIVE
        INACTIVE: :INACTIVE
        SUSPENDED: :SUSPENDED

        def self?.values: -> ::Array[SentDm::Models::BrandWithKYC::status]
      end
    end
  end
end
