module SentDm
  module Models
    type contact_list_response =
      {
        data: SentDm::Models::ContactListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class ContactListResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::ContactListResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::ContactListResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::ContactListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data =
        {
          contacts: ::Array[SentDm::Contact],
          pagination: SentDm::PaginationMeta
        }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader contacts: ::Array[SentDm::Contact]?

        def contacts=: (::Array[SentDm::Contact]) -> ::Array[SentDm::Contact]

        attr_reader pagination: SentDm::PaginationMeta?

        def pagination=: (SentDm::PaginationMeta) -> SentDm::PaginationMeta

        def initialize: (
          ?contacts: ::Array[SentDm::Contact],
          ?pagination: SentDm::PaginationMeta
        ) -> void

        def to_hash: -> {
          contacts: ::Array[SentDm::Contact],
          pagination: SentDm::PaginationMeta
        }
      end
    end
  end
end
