module SentDm
  module Models
    type contact_retrieve_id_params =
      { id: String } & SentDm::Internal::Type::request_parameters

    class ContactRetrieveIDParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: SentDm::RequestOptions }
    end
  end
end
