module SentDm
  module Models
    type contact =
      {
        id: String,
        available_channels: String,
        country_code: String,
        created_at: Time,
        default_channel: String,
        :format_e164 => String,
        format_international: String,
        format_national: String,
        format_rfc: String,
        is_inherited: bool,
        opt_out: bool,
        phone_number: String,
        region_code: String,
        updated_at: Time?
      }

    class Contact < SentDm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader available_channels: String?

      def available_channels=: (String) -> String

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader default_channel: String?

      def default_channel=: (String) -> String

      attr_reader format_e164: String?

      def format_e164=: (String) -> String

      attr_reader format_international: String?

      def format_international=: (String) -> String

      attr_reader format_national: String?

      def format_national=: (String) -> String

      attr_reader format_rfc: String?

      def format_rfc=: (String) -> String

      attr_reader is_inherited: bool?

      def is_inherited=: (bool) -> bool

      attr_reader opt_out: bool?

      def opt_out=: (bool) -> bool

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader region_code: String?

      def region_code=: (String) -> String

      attr_accessor updated_at: Time?

      def initialize: (
        ?id: String,
        ?available_channels: String,
        ?country_code: String,
        ?created_at: Time,
        ?default_channel: String,
        ?format_e164: String,
        ?format_international: String,
        ?format_national: String,
        ?format_rfc: String,
        ?is_inherited: bool,
        ?opt_out: bool,
        ?phone_number: String,
        ?region_code: String,
        ?updated_at: Time?
      ) -> void

      def to_hash: -> {
        id: String,
        available_channels: String,
        country_code: String,
        created_at: Time,
        default_channel: String,
        :format_e164 => String,
        format_international: String,
        format_national: String,
        format_rfc: String,
        is_inherited: bool,
        opt_out: bool,
        phone_number: String,
        region_code: String,
        updated_at: Time?
      }
    end
  end
end
