module SentDm
  module Models
    type contact_create_params =
      { phone_number: String, test_mode: bool, idempotency_key: String }
      & SentDm::Internal::Type::request_parameters

    class ContactCreateParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?phone_number: String,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        phone_number: String,
        test_mode: bool,
        idempotency_key: String,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
