module SentDm
  module Models
    type lookup_retrieve_phone_info_params =
      {  } & SentDm::Internal::Type::request_parameters

    class LookupRetrievePhoneInfoParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      def initialize: (?request_options: SentDm::request_opts) -> void

      def to_hash: -> { request_options: SentDm::RequestOptions }
    end
  end
end
