module SentDm
  module Models
    type message_send_to_contact_params =
      {
        contact_id: String,
        template_id: String,
        template_variables: ::Hash[Symbol, String]?
      }
      & SentDm::Internal::Type::request_parameters

    class MessageSendToContactParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor contact_id: String

      attr_accessor template_id: String

      attr_accessor template_variables: ::Hash[Symbol, String]?

      def initialize: (
        contact_id: String,
        template_id: String,
        ?template_variables: ::Hash[Symbol, String]?,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        contact_id: String,
        template_id: String,
        template_variables: ::Hash[Symbol, String]?,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
