module SentDm
  module Models
    type message_retrieve_activities_response =
      {
        data: SentDm::Models::MessageRetrieveActivitiesResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class MessageRetrieveActivitiesResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::MessageRetrieveActivitiesResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::MessageRetrieveActivitiesResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::MessageRetrieveActivitiesResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data =
        {
          activities: ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          message_id: String
        }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader activities: ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity]?

        def activities=: (
          ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity]
        ) -> ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity]

        attr_reader message_id: String?

        def message_id=: (String) -> String

        def initialize: (
          ?activities: ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          ?message_id: String
        ) -> void

        def to_hash: -> {
          activities: ::Array[SentDm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          message_id: String
        }

        type activity =
          {
            content: String?,
            description: String,
            status: String,
            timestamp: Time
          }

        class Activity < SentDm::Internal::Type::BaseModel
          attr_accessor content: String?

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader status: String?

          def status=: (String) -> String

          attr_reader timestamp: Time?

          def timestamp=: (Time) -> Time

          def initialize: (
            ?content: String?,
            ?description: String,
            ?status: String,
            ?timestamp: Time
          ) -> void

          def to_hash: -> {
            content: String?,
            description: String,
            status: String,
            timestamp: Time
          }
        end
      end
    end
  end
end
