module SentDm
  module Models
    type message_send_quick_message_params =
      { custom_message: String, phone_number: String }
      & SentDm::Internal::Type::request_parameters

    class MessageSendQuickMessageParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor custom_message: String

      attr_accessor phone_number: String

      def initialize: (
        custom_message: String,
        phone_number: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        custom_message: String,
        phone_number: String,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
