module SentDm
  module Models
    type message_retrieve_params =
      { x_api_key: String, x_sender_id: String }
      & SentDm::Internal::Type::request_parameters

    class MessageRetrieveParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor x_api_key: String

      attr_accessor x_sender_id: String

      def initialize: (
        x_api_key: String,
        x_sender_id: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        x_api_key: String,
        x_sender_id: String,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
