module SentDm
  module Models
    type organization_retrieve_profiles_response =
      { organization_id: String, profiles: ::Array[SentDm::ProfileSummary] }

    class OrganizationRetrieveProfilesResponse < SentDm::Internal::Type::BaseModel
      attr_reader organization_id: String?

      def organization_id=: (String) -> String

      attr_reader profiles: ::Array[SentDm::ProfileSummary]?

      def profiles=: (
        ::Array[SentDm::ProfileSummary]
      ) -> ::Array[SentDm::ProfileSummary]

      def initialize: (
        ?organization_id: String,
        ?profiles: ::Array[SentDm::ProfileSummary]
      ) -> void

      def to_hash: -> {
        organization_id: String,
        profiles: ::Array[SentDm::ProfileSummary]
      }
    end
  end
end
