module SentDm
  module Models
    type pagination_meta =
      {
        cursors: SentDm::PaginationMeta::Cursors?,
        has_more: bool,
        page: Integer,
        page_size: Integer,
        total_count: Integer,
        total_pages: Integer
      }

    class PaginationMeta < SentDm::Internal::Type::BaseModel
      attr_accessor cursors: SentDm::PaginationMeta::Cursors?

      attr_reader has_more: bool?

      def has_more=: (bool) -> bool

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader total_count: Integer?

      def total_count=: (Integer) -> Integer

      attr_reader total_pages: Integer?

      def total_pages=: (Integer) -> Integer

      def initialize: (
        ?cursors: SentDm::PaginationMeta::Cursors?,
        ?has_more: bool,
        ?page: Integer,
        ?page_size: Integer,
        ?total_count: Integer,
        ?total_pages: Integer
      ) -> void

      def to_hash: -> {
        cursors: SentDm::PaginationMeta::Cursors?,
        has_more: bool,
        page: Integer,
        page_size: Integer,
        total_count: Integer,
        total_pages: Integer
      }

      type cursors = { after: String?, before: String? }

      class Cursors < SentDm::Internal::Type::BaseModel
        attr_accessor after: String?

        attr_accessor before: String?

        def initialize: (?after: String?, ?before: String?) -> void

        def to_hash: -> { after: String?, before: String? }
      end
    end
  end
end
