module SentDm
  module Models
    type template_body_content =
      {
        template: String,
        type: String?,
        variables: ::Array[SentDm::TemplateVariable]?
      }

    class TemplateBodyContent < SentDm::Internal::Type::BaseModel
      attr_reader template: String?

      def template=: (String) -> String

      attr_accessor type: String?

      attr_accessor variables: ::Array[SentDm::TemplateVariable]?

      def initialize: (
        ?template: String,
        ?type: String?,
        ?variables: ::Array[SentDm::TemplateVariable]?
      ) -> void

      def to_hash: -> {
        template: String,
        type: String?,
        variables: ::Array[SentDm::TemplateVariable]?
      }
    end
  end
end
