module SentDm
  module Models
    type template_list_params =
      {
        page: Integer,
        page_size: Integer,
        x_api_key: String,
        x_sender_id: String,
        category: String?,
        search: String?,
        status: String?
      }
      & SentDm::Internal::Type::request_parameters

    class TemplateListParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor page: Integer

      attr_accessor page_size: Integer

      attr_accessor x_api_key: String

      attr_accessor x_sender_id: String

      attr_accessor category: String?

      attr_accessor search: String?

      attr_accessor status: String?

      def initialize: (
        page: Integer,
        page_size: Integer,
        x_api_key: String,
        x_sender_id: String,
        ?category: String?,
        ?search: String?,
        ?status: String?,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        page: Integer,
        page_size: Integer,
        x_api_key: String,
        x_sender_id: String,
        category: String?,
        search: String?,
        status: String?,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
