module SentDm
  module Models
    type template_update_params =
      {
        category: String?,
        definition: SentDm::TemplateDefinition?,
        language: String?,
        name: String?,
        submit_for_review: bool,
        test_mode: bool,
        idempotency_key: String
      }
      & SentDm::Internal::Type::request_parameters

    class TemplateUpdateParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor category: String?

      attr_accessor definition: SentDm::TemplateDefinition?

      attr_accessor language: String?

      attr_accessor name: String?

      attr_reader submit_for_review: bool?

      def submit_for_review=: (bool) -> bool

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?category: String?,
        ?definition: SentDm::TemplateDefinition?,
        ?language: String?,
        ?name: String?,
        ?submit_for_review: bool,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        category: String?,
        definition: SentDm::TemplateDefinition?,
        language: String?,
        name: String?,
        submit_for_review: bool,
        test_mode: bool,
        idempotency_key: String,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
