module SentDm
  module Models
    type template_delete_params =
      { delete_from_meta: bool?, test_mode: bool }
      & SentDm::Internal::Type::request_parameters

    class TemplateDeleteParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor delete_from_meta: bool?

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      def initialize: (
        ?delete_from_meta: bool?,
        ?test_mode: bool,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        delete_from_meta: bool?,
        test_mode: bool,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
