module SentDm
  module Models
    type template_create_params =
      {
        definition: SentDm::TemplateDefinition,
        x_api_key: String,
        x_sender_id: String,
        category: String?,
        language: String?,
        submit_for_review: bool
      }
      & SentDm::Internal::Type::request_parameters

    class TemplateCreateParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor definition: SentDm::TemplateDefinition

      attr_accessor x_api_key: String

      attr_accessor x_sender_id: String

      attr_accessor category: String?

      attr_accessor language: String?

      attr_reader submit_for_review: bool?

      def submit_for_review=: (bool) -> bool

      def initialize: (
        definition: SentDm::TemplateDefinition,
        x_api_key: String,
        x_sender_id: String,
        ?category: String?,
        ?language: String?,
        ?submit_for_review: bool,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        definition: SentDm::TemplateDefinition,
        x_api_key: String,
        x_sender_id: String,
        category: String?,
        language: String?,
        submit_for_review: bool,
        request_options: SentDm::RequestOptions
      }
    end
  end
end
