module SentDm
  module Models
    type user_list_response =
      {
        data: SentDm::Models::UserListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class UserListResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::UserListResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::UserListResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::UserListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data = { users: ::Array[SentDm::UserResponse] }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader users: ::Array[SentDm::UserResponse]?

        def users=: (
          ::Array[SentDm::UserResponse]
        ) -> ::Array[SentDm::UserResponse]

        def initialize: (?users: ::Array[SentDm::UserResponse]) -> void

        def to_hash: -> { users: ::Array[SentDm::UserResponse] }
      end
    end
  end
end
