module SentDm
  module Models
    type user_list_params = {  } & SentDm::Internal::Type::request_parameters

    class UserListParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      def initialize: (?request_options: SentDm::request_opts) -> void

      def to_hash: -> { request_options: SentDm::RequestOptions }
    end
  end
end
