module SentDm
  module Models
    type webhook_rotate_secret_params =
      { body: SentDm::WebhookRotateSecretParams::Body, idempotency_key: String }
      & SentDm::Internal::Type::request_parameters

    class WebhookRotateSecretParams < SentDm::Internal::Type::BaseModel
      extend SentDm::Internal::Type::RequestParameters::Converter
      include SentDm::Internal::Type::RequestParameters

      attr_accessor body: SentDm::WebhookRotateSecretParams::Body

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        body: SentDm::WebhookRotateSecretParams::Body,
        ?idempotency_key: String,
        ?request_options: SentDm::request_opts
      ) -> void

      def to_hash: -> {
        body: SentDm::WebhookRotateSecretParams::Body,
        idempotency_key: String,
        request_options: SentDm::RequestOptions
      }

      type body = {  }

      class Body < SentDm::Models::MutationRequest
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
