module SentDm
  module Models
    type webhook_test_response =
      {
        data: SentDm::Models::WebhookTestResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class WebhookTestResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::WebhookTestResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::WebhookTestResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::WebhookTestResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data = { message: String, success: bool }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader message: String?

        def message=: (String) -> String

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (?message: String, ?success: bool) -> void

        def to_hash: -> { message: String, success: bool }
      end
    end
  end
end
