module SentDm
  module Models
    type webhook_list_response =
      {
        data: SentDm::Models::WebhookListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class WebhookListResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::WebhookListResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::WebhookListResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::WebhookListResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data =
        {
          pagination: SentDm::PaginationMeta,
          webhooks: ::Array[SentDm::WebhookResponse]
        }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader pagination: SentDm::PaginationMeta?

        def pagination=: (SentDm::PaginationMeta) -> SentDm::PaginationMeta

        attr_reader webhooks: ::Array[SentDm::WebhookResponse]?

        def webhooks=: (
          ::Array[SentDm::WebhookResponse]
        ) -> ::Array[SentDm::WebhookResponse]

        def initialize: (
          ?pagination: SentDm::PaginationMeta,
          ?webhooks: ::Array[SentDm::WebhookResponse]
        ) -> void

        def to_hash: -> {
          pagination: SentDm::PaginationMeta,
          webhooks: ::Array[SentDm::WebhookResponse]
        }
      end
    end
  end
end
