module SentDm
  module Models
    type webhook_rotate_secret_response =
      {
        data: SentDm::Models::WebhookRotateSecretResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

    class WebhookRotateSecretResponse < SentDm::Internal::Type::BaseModel
      attr_accessor data: SentDm::Models::WebhookRotateSecretResponse::Data?

      attr_accessor error: SentDm::APIError?

      attr_reader meta: SentDm::APIMeta?

      def meta=: (SentDm::APIMeta) -> SentDm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: SentDm::Models::WebhookRotateSecretResponse::Data?,
        ?error: SentDm::APIError?,
        ?meta: SentDm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: SentDm::Models::WebhookRotateSecretResponse::Data?,
        error: SentDm::APIError?,
        meta: SentDm::APIMeta,
        success: bool
      }

      type data = { signing_secret: String }

      class Data < SentDm::Internal::Type::BaseModel
        attr_reader signing_secret: String?

        def signing_secret=: (String) -> String

        def initialize: (?signing_secret: String) -> void

        def to_hash: -> { signing_secret: String }
      end
    end
  end
end
