module Sentdm
  module Models
    module Channels
      type api_response_of_voice_secret =
        {
          data: Sentdm::Channels::VoiceSecret?,
          error: Sentdm::ErrorDetail?,
          meta: Sentdm::APIMeta,
          success: bool
        }

      class APIResponseOfVoiceSecret < Sentdm::Internal::Type::BaseModel
        attr_accessor data: Sentdm::Channels::VoiceSecret?

        attr_accessor error: Sentdm::ErrorDetail?

        attr_reader meta: Sentdm::APIMeta?

        def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (
          ?data: Sentdm::Channels::VoiceSecret?,
          ?error: Sentdm::ErrorDetail?,
          ?meta: Sentdm::APIMeta,
          ?success: bool
        ) -> void

        def to_hash: -> {
          data: Sentdm::Channels::VoiceSecret?,
          error: Sentdm::ErrorDetail?,
          meta: Sentdm::APIMeta,
          success: bool
        }
      end
    end
  end
end
