module Sentdm
  module Models
    module Channels
      type voice_secret = { callback_secret: String }

      class VoiceSecret < Sentdm::Internal::Type::BaseModel
        attr_reader callback_secret: String?

        def callback_secret=: (String) -> String

        def initialize: (?callback_secret: String) -> void

        def to_hash: -> { callback_secret: String }
      end
    end
  end
end
