module Sentdm
  module Internal
    class ContactsPage[Elem]
      include Sentdm::Internal::Type::BasePage[Elem]

      attr_accessor data: Data

      def inspect: -> String

      type data = { contacts: ::Array[top], pagination: Data::Pagination }
      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader contacts: ::Array[top]?

        def contacts=: (::Array[top]) -> ::Array[top]

        attr_reader pagination: Data::Pagination?

        def pagination=: (Data::Pagination) -> Data::Pagination

        def initialize: (
          ?contacts: ::Array[top],
          ?pagination: Data::Pagination
        ) -> void

        def to_hash: -> { contacts: ::Array[top], pagination: Data::Pagination }

        type pagination = { has_more: bool }

        class Pagination < Sentdm::Internal::Type::BaseModel
          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          def initialize: (?has_more: bool) -> void

          def to_hash: -> { has_more: bool }
        end
      end
    end
  end
end
