module Sentdm
  module Internal
    class WebhooksPage[Elem]
      include Sentdm::Internal::Type::BasePage[Elem]

      attr_accessor data: Data

      def inspect: -> String

      type data = { pagination: Data::Pagination, webhooks: ::Array[top] }
      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader pagination: Data::Pagination?

        def pagination=: (Data::Pagination) -> Data::Pagination

        attr_reader webhooks: ::Array[top]?

        def webhooks=: (::Array[top]) -> ::Array[top]

        def initialize: (
          ?pagination: Data::Pagination,
          ?webhooks: ::Array[top]
        ) -> void

        def to_hash: -> { pagination: Data::Pagination, webhooks: ::Array[top] }

        type pagination = { has_more: bool }

        class Pagination < Sentdm::Internal::Type::BaseModel
          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          def initialize: (?has_more: bool) -> void

          def to_hash: -> { has_more: bool }
        end
      end
    end
  end
end
