module Sentdm
  module Models
    module Organizations
      type user_invite_params =
        { email: String, invited_by: String?, name: String, role: String }
        & Sentdm::Internal::Type::request_parameters

      class UserInviteParams < Sentdm::Internal::Type::BaseModel
        extend Sentdm::Internal::Type::RequestParameters::Converter
        include Sentdm::Internal::Type::RequestParameters

        attr_reader email: String?

        def email=: (String) -> String

        attr_accessor invited_by: String?

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader role: String?

        def role=: (String) -> String

        def initialize: (
          ?email: String,
          ?invited_by: String?,
          ?name: String,
          ?role: String,
          ?request_options: Sentdm::request_opts
        ) -> void

        def to_hash: -> {
          email: String,
          invited_by: String?,
          name: String,
          role: String,
          request_options: Sentdm::RequestOptions
        }
      end
    end
  end
end
