module Sentdm
  module Models
    module Organizations
      type user_list_params =
        { page: Integer, page_size: Integer }
        & Sentdm::Internal::Type::request_parameters

      class UserListParams < Sentdm::Internal::Type::BaseModel
        extend Sentdm::Internal::Type::RequestParameters::Converter
        include Sentdm::Internal::Type::RequestParameters

        attr_accessor page: Integer

        attr_accessor page_size: Integer

        def initialize: (
          page: Integer,
          page_size: Integer,
          ?request_options: Sentdm::request_opts
        ) -> void

        def to_hash: -> {
          page: Integer,
          page_size: Integer,
          request_options: Sentdm::RequestOptions
        }
      end
    end
  end
end
