module Sentdm
  module Models
    type api_response_of_call_recordings =
      {
        data: Sentdm::CallRecordings?,
        error: Sentdm::ErrorDetail?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class APIResponseOfCallRecordings < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::CallRecordings?

      attr_accessor error: Sentdm::ErrorDetail?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::CallRecordings?,
        ?error: Sentdm::ErrorDetail?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::CallRecordings?,
        error: Sentdm::ErrorDetail?,
        meta: Sentdm::APIMeta,
        success: bool
      }
    end
  end
end
