module Sentdm
  module Models
    type api_response_of_profile_detail =
      {
        data: Sentdm::ProfileDetail?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class APIResponseOfProfileDetail < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::ProfileDetail?

      attr_accessor error: Sentdm::APIError?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::ProfileDetail?,
        ?error: Sentdm::APIError?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::ProfileDetail?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }
    end
  end
end
