module Sentdm
  module Models
    type brand_update_params =
      { brand: Sentdm::BrandData, test_mode: bool, idempotency_key: String }
      & Sentdm::Internal::Type::request_parameters

    class BrandUpdateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor brand: Sentdm::BrandData

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        brand: Sentdm::BrandData,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        brand: Sentdm::BrandData,
        test_mode: bool,
        idempotency_key: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
