module Sentdm
  module Models
    type brand_with_kyc =
      {
        id: String,
        business: Sentdm::BrandWithKYC::Business?,
        compliance: Sentdm::BrandWithKYC::Compliance?,
        contact: Sentdm::BrandWithKYC::Contact?,
        created_at: Time,
        csp_id: String?,
        identity_status: Sentdm::Models::BrandWithKYC::identity_status?,
        is_inherited: bool,
        status: Sentdm::Models::BrandWithKYC::status?,
        submitted_at: Time?,
        submitted_to_tcr: bool,
        tcr_brand_id: String?,
        universal_ein: String?,
        updated_at: Time?
      }

    class BrandWithKYC < Sentdm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_accessor business: Sentdm::BrandWithKYC::Business?

      attr_accessor compliance: Sentdm::BrandWithKYC::Compliance?

      attr_accessor contact: Sentdm::BrandWithKYC::Contact?

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_accessor csp_id: String?

      attr_accessor identity_status: Sentdm::Models::BrandWithKYC::identity_status?

      attr_reader is_inherited: bool?

      def is_inherited=: (bool) -> bool

      attr_accessor status: Sentdm::Models::BrandWithKYC::status?

      attr_accessor submitted_at: Time?

      attr_reader submitted_to_tcr: bool?

      def submitted_to_tcr=: (bool) -> bool

      attr_accessor tcr_brand_id: String?

      attr_accessor universal_ein: String?

      attr_accessor updated_at: Time?

      def initialize: (
        ?id: String,
        ?business: Sentdm::BrandWithKYC::Business?,
        ?compliance: Sentdm::BrandWithKYC::Compliance?,
        ?contact: Sentdm::BrandWithKYC::Contact?,
        ?created_at: Time,
        ?csp_id: String?,
        ?identity_status: Sentdm::Models::BrandWithKYC::identity_status?,
        ?is_inherited: bool,
        ?status: Sentdm::Models::BrandWithKYC::status?,
        ?submitted_at: Time?,
        ?submitted_to_tcr: bool,
        ?tcr_brand_id: String?,
        ?universal_ein: String?,
        ?updated_at: Time?
      ) -> void

      def to_hash: -> {
        id: String,
        business: Sentdm::BrandWithKYC::Business?,
        compliance: Sentdm::BrandWithKYC::Compliance?,
        contact: Sentdm::BrandWithKYC::Contact?,
        created_at: Time,
        csp_id: String?,
        identity_status: Sentdm::Models::BrandWithKYC::identity_status?,
        is_inherited: bool,
        status: Sentdm::Models::BrandWithKYC::status?,
        submitted_at: Time?,
        submitted_to_tcr: bool,
        tcr_brand_id: String?,
        universal_ein: String?,
        updated_at: Time?
      }

      type business =
        {
          city: String?,
          country: String?,
          country_of_registration: String?,
          entity_type: String?,
          legal_name: String?,
          postal_code: String?,
          state: String?,
          street: String?,
          tax_id: String?,
          tax_id_type: String?,
          url: String?
        }

      class Business < Sentdm::Internal::Type::BaseModel
        attr_accessor city: String?

        attr_accessor country: String?

        attr_accessor country_of_registration: String?

        attr_accessor entity_type: String?

        attr_accessor legal_name: String?

        attr_accessor postal_code: String?

        attr_accessor state: String?

        attr_accessor street: String?

        attr_accessor tax_id: String?

        attr_accessor tax_id_type: String?

        attr_accessor url: String?

        def initialize: (
          ?city: String?,
          ?country: String?,
          ?country_of_registration: String?,
          ?entity_type: String?,
          ?legal_name: String?,
          ?postal_code: String?,
          ?state: String?,
          ?street: String?,
          ?tax_id: String?,
          ?tax_id_type: String?,
          ?url: String?
        ) -> void

        def to_hash: -> {
          city: String?,
          country: String?,
          country_of_registration: String?,
          entity_type: String?,
          legal_name: String?,
          postal_code: String?,
          state: String?,
          street: String?,
          tax_id: String?,
          tax_id_type: String?,
          url: String?
        }
      end

      type compliance =
        {
          brand_relationship: Sentdm::Models::tcr_brand_relationship?,
          destination_countries: ::Array[Sentdm::DestinationCountry],
          expected_messaging_volume: String?,
          is_tcr_application: bool,
          notes: String?,
          phone_number_prefix: String?,
          primary_use_case: String?,
          vertical: Sentdm::Models::tcr_vertical?
        }

      class Compliance < Sentdm::Internal::Type::BaseModel
        attr_accessor brand_relationship: Sentdm::Models::tcr_brand_relationship?

        attr_reader destination_countries: ::Array[Sentdm::DestinationCountry]?

        def destination_countries=: (
          ::Array[Sentdm::DestinationCountry]
        ) -> ::Array[Sentdm::DestinationCountry]

        attr_accessor expected_messaging_volume: String?

        attr_reader is_tcr_application: bool?

        def is_tcr_application=: (bool) -> bool

        attr_accessor notes: String?

        attr_accessor phone_number_prefix: String?

        attr_accessor primary_use_case: String?

        attr_accessor vertical: Sentdm::Models::tcr_vertical?

        def initialize: (
          ?brand_relationship: Sentdm::Models::tcr_brand_relationship?,
          ?destination_countries: ::Array[Sentdm::DestinationCountry],
          ?expected_messaging_volume: String?,
          ?is_tcr_application: bool,
          ?notes: String?,
          ?phone_number_prefix: String?,
          ?primary_use_case: String?,
          ?vertical: Sentdm::Models::tcr_vertical?
        ) -> void

        def to_hash: -> {
          brand_relationship: Sentdm::Models::tcr_brand_relationship?,
          destination_countries: ::Array[Sentdm::DestinationCountry],
          expected_messaging_volume: String?,
          is_tcr_application: bool,
          notes: String?,
          phone_number_prefix: String?,
          primary_use_case: String?,
          vertical: Sentdm::Models::tcr_vertical?
        }
      end

      type contact =
        {
          business_name: String?,
          email: String?,
          name: String,
          phone: String?,
          phone_country_code: String?,
          role: String?
        }

      class Contact < Sentdm::Internal::Type::BaseModel
        attr_accessor business_name: String?

        attr_accessor email: String?

        attr_reader name: String?

        def name=: (String) -> String

        attr_accessor phone: String?

        attr_accessor phone_country_code: String?

        attr_accessor role: String?

        def initialize: (
          ?business_name: String?,
          ?email: String?,
          ?name: String,
          ?phone: String?,
          ?phone_country_code: String?,
          ?role: String?
        ) -> void

        def to_hash: -> {
          business_name: String?,
          email: String?,
          name: String,
          phone: String?,
          phone_country_code: String?,
          role: String?
        }
      end

      type identity_status =
        :SELF_DECLARED | :UNVERIFIED | :VERIFIED | :VETTED_VERIFIED

      module IdentityStatus
        extend Sentdm::Internal::Type::Enum

        SELF_DECLARED: :SELF_DECLARED
        UNVERIFIED: :UNVERIFIED
        VERIFIED: :VERIFIED
        VETTED_VERIFIED: :VETTED_VERIFIED

        def self?.values: -> ::Array[Sentdm::Models::BrandWithKYC::identity_status]
      end

      type status = :ACTIVE | :INACTIVE | :SUSPENDED

      module Status
        extend Sentdm::Internal::Type::Enum

        ACTIVE: :ACTIVE
        INACTIVE: :INACTIVE
        SUSPENDED: :SUSPENDED

        def self?.values: -> ::Array[Sentdm::Models::BrandWithKYC::status]
      end
    end
  end
end
