module Sentdm
  module Models
    type channel_event_payload =
      {
        country: String,
        account_id: String,
        channel: String,
        number_type: String?,
        reason: String?,
        sender_value: String?,
        status: String,
        updated_at: String
      }

    class ChannelEventPayload < Sentdm::Internal::Type::BaseModel
      attr_accessor country: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader channel: String?

      def channel=: (String) -> String

      attr_accessor number_type: String?

      attr_accessor reason: String?

      attr_accessor sender_value: String?

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader updated_at: String?

      def updated_at=: (String) -> String

      def initialize: (
        country: String,
        ?account_id: String,
        ?channel: String,
        ?number_type: String?,
        ?reason: String?,
        ?sender_value: String?,
        ?status: String,
        ?updated_at: String
      ) -> void

      def to_hash: -> {
        country: String,
        account_id: String,
        channel: String,
        number_type: String?,
        reason: String?,
        sender_value: String?,
        status: String,
        updated_at: String
      }
    end
  end
end
