module Sentdm
  module Models
    type contact_event_payload =
      {
        opt_out: bool,
        source: String,
        account_id: String,
        agent_id: String?,
        channel: String,
        contact_id: String,
        from: String,
        message_id: String?,
        template_id: String?,
        text: String?,
        to: String?
      }

    class ContactEventPayload < Sentdm::Internal::Type::BaseModel
      attr_accessor opt_out: bool

      attr_accessor source: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_accessor agent_id: String?

      attr_reader channel: String?

      def channel=: (String) -> String

      attr_reader contact_id: String?

      def contact_id=: (String) -> String

      attr_reader from: String?

      def from=: (String) -> String

      attr_accessor message_id: String?

      attr_accessor template_id: String?

      attr_accessor text: String?

      attr_accessor to: String?

      def initialize: (
        opt_out: bool,
        source: String,
        ?account_id: String,
        ?agent_id: String?,
        ?channel: String,
        ?contact_id: String,
        ?from: String,
        ?message_id: String?,
        ?template_id: String?,
        ?text: String?,
        ?to: String?
      ) -> void

      def to_hash: -> {
        opt_out: bool,
        source: String,
        account_id: String,
        agent_id: String?,
        channel: String,
        contact_id: String,
        from: String,
        message_id: String?,
        template_id: String?,
        text: String?,
        to: String?
      }
    end
  end
end
