module Sentdm
  module Models
    type contact_list_params =
      {
        channel: String?,
        page: Integer,
        page_size: Integer,
        phone: String?,
        search: String?,
        x_profile_id: String
      }
      & Sentdm::Internal::Type::request_parameters

    class ContactListParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor channel: String?

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_accessor phone: String?

      attr_accessor search: String?

      attr_reader x_profile_id: String?

      def x_profile_id=: (String) -> String

      def initialize: (
        ?channel: String?,
        ?page: Integer,
        ?page_size: Integer,
        ?phone: String?,
        ?search: String?,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        channel: String?,
        page: Integer,
        page_size: Integer,
        phone: String?,
        search: String?,
        x_profile_id: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
