module Sentdm
  module Models
    type contact_delete_params =
      { body: Sentdm::ContactDeleteParams::Body }
      & Sentdm::Internal::Type::request_parameters

    class ContactDeleteParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor body: Sentdm::ContactDeleteParams::Body

      def initialize: (
        body: Sentdm::ContactDeleteParams::Body,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        body: Sentdm::ContactDeleteParams::Body,
        request_options: Sentdm::RequestOptions
      }

      type body = {  }

      class Body < Sentdm::Models::MutationRequest
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
