module Sentdm
  module Models
    type contact_update_params =
      {
        default_channel: String?,
        opt_out: bool?,
        test_mode: bool,
        idempotency_key: String
      }
      & Sentdm::Internal::Type::request_parameters

    class ContactUpdateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor default_channel: String?

      attr_accessor opt_out: bool?

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?default_channel: String?,
        ?opt_out: bool?,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        default_channel: String?,
        opt_out: bool?,
        test_mode: bool,
        idempotency_key: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
