module Sentdm
  module Models
    type contact_create_response =
      {
        data: Sentdm::Models::ContactCreateResponse::Data?,
        error: Sentdm::Models::ContactCreateResponse::Error?,
        meta: Sentdm::Models::ContactCreateResponse::Meta,
        success: bool
      }

    class ContactCreateResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::ContactCreateResponse::Data?

      attr_accessor error: Sentdm::Models::ContactCreateResponse::Error?

      attr_reader meta: Sentdm::Models::ContactCreateResponse::Meta?

      def meta=: (
        Sentdm::Models::ContactCreateResponse::Meta
      ) -> Sentdm::Models::ContactCreateResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::ContactCreateResponse::Data?,
        ?error: Sentdm::Models::ContactCreateResponse::Error?,
        ?meta: Sentdm::Models::ContactCreateResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::ContactCreateResponse::Data?,
        error: Sentdm::Models::ContactCreateResponse::Error?,
        meta: Sentdm::Models::ContactCreateResponse::Meta,
        success: bool
      }

      type data =
        {
          id: String,
          available_channels: String,
          country_code: String,
          created_at: Time,
          default_channel: String,
          :format_e164 => String,
          format_international: String,
          format_national: String,
          format_rfc: String,
          is_inherited: bool,
          opt_out: bool,
          phone_number: String,
          region_code: String,
          updated_at: Time?
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader available_channels: String?

        def available_channels=: (String) -> String

        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader default_channel: String?

        def default_channel=: (String) -> String

        attr_reader format_e164: String?

        def format_e164=: (String) -> String

        attr_reader format_international: String?

        def format_international=: (String) -> String

        attr_reader format_national: String?

        def format_national=: (String) -> String

        attr_reader format_rfc: String?

        def format_rfc=: (String) -> String

        attr_reader is_inherited: bool?

        def is_inherited=: (bool) -> bool

        attr_reader opt_out: bool?

        def opt_out=: (bool) -> bool

        attr_reader phone_number: String?

        def phone_number=: (String) -> String

        attr_reader region_code: String?

        def region_code=: (String) -> String

        attr_accessor updated_at: Time?

        def initialize: (
          ?id: String,
          ?available_channels: String,
          ?country_code: String,
          ?created_at: Time,
          ?default_channel: String,
          ?format_e164: String,
          ?format_international: String,
          ?format_national: String,
          ?format_rfc: String,
          ?is_inherited: bool,
          ?opt_out: bool,
          ?phone_number: String,
          ?region_code: String,
          ?updated_at: Time?
        ) -> void

        def to_hash: -> {
          id: String,
          available_channels: String,
          country_code: String,
          created_at: Time,
          default_channel: String,
          :format_e164 => String,
          format_international: String,
          format_national: String,
          format_rfc: String,
          is_inherited: bool,
          opt_out: bool,
          phone_number: String,
          region_code: String,
          updated_at: Time?
        }
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
