module Sentdm
  module Models
    type contact_message_summary =
      {
        channel_scores: ::Array[Sentdm::ContactMessageSummary::ChannelScore],
        channels_used: ::Array[String],
        contact_id: String,
        first_message_at: Time?,
        last_message_at: Time?,
        message_count: Integer
      }

    class ContactMessageSummary < Sentdm::Internal::Type::BaseModel
      attr_reader channel_scores: ::Array[Sentdm::ContactMessageSummary::ChannelScore]?

      def channel_scores=: (
        ::Array[Sentdm::ContactMessageSummary::ChannelScore]
      ) -> ::Array[Sentdm::ContactMessageSummary::ChannelScore]

      attr_reader channels_used: ::Array[String]?

      def channels_used=: (::Array[String]) -> ::Array[String]

      attr_reader contact_id: String?

      def contact_id=: (String) -> String

      attr_accessor first_message_at: Time?

      attr_accessor last_message_at: Time?

      attr_reader message_count: Integer?

      def message_count=: (Integer) -> Integer

      def initialize: (
        ?channel_scores: ::Array[Sentdm::ContactMessageSummary::ChannelScore],
        ?channels_used: ::Array[String],
        ?contact_id: String,
        ?first_message_at: Time?,
        ?last_message_at: Time?,
        ?message_count: Integer
      ) -> void

      def to_hash: -> {
        channel_scores: ::Array[Sentdm::ContactMessageSummary::ChannelScore],
        channels_used: ::Array[String],
        contact_id: String,
        first_message_at: Time?,
        last_message_at: Time?,
        message_count: Integer
      }

      type channel_score =
        { channel: String, fail_score: Integer, success_score: Integer }

      class ChannelScore < Sentdm::Internal::Type::BaseModel
        attr_reader channel: String?

        def channel=: (String) -> String

        attr_reader fail_score: Integer?

        def fail_score=: (Integer) -> Integer

        attr_reader success_score: Integer?

        def success_score=: (Integer) -> Integer

        def initialize: (
          ?channel: String,
          ?fail_score: Integer,
          ?success_score: Integer
        ) -> void

        def to_hash: -> {
          channel: String,
          fail_score: Integer,
          success_score: Integer
        }
      end
    end
  end
end
