module Sentdm
  module Models
    type contact_retrieve_message_summary_response =
      {
        data: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data?,
        error: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Error?,
        meta: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta,
        success: bool
      }

    class ContactRetrieveMessageSummaryResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data?

      attr_accessor error: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Error?

      attr_reader meta: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta?

      def meta=: (
        Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta
      ) -> Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data?,
        ?error: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Error?,
        ?meta: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data?,
        error: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Error?,
        meta: Sentdm::Models::ContactRetrieveMessageSummaryResponse::Meta,
        success: bool
      }

      type data =
        {
          channel_scores: ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore],
          channels_used: ::Array[String],
          contact_id: String,
          first_message_at: Time?,
          last_message_at: Time?,
          message_count: Integer
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader channel_scores: ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore]?

        def channel_scores=: (
          ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore]
        ) -> ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore]

        attr_reader channels_used: ::Array[String]?

        def channels_used=: (::Array[String]) -> ::Array[String]

        attr_reader contact_id: String?

        def contact_id=: (String) -> String

        attr_accessor first_message_at: Time?

        attr_accessor last_message_at: Time?

        attr_reader message_count: Integer?

        def message_count=: (Integer) -> Integer

        def initialize: (
          ?channel_scores: ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore],
          ?channels_used: ::Array[String],
          ?contact_id: String,
          ?first_message_at: Time?,
          ?last_message_at: Time?,
          ?message_count: Integer
        ) -> void

        def to_hash: -> {
          channel_scores: ::Array[Sentdm::Models::ContactRetrieveMessageSummaryResponse::Data::ChannelScore],
          channels_used: ::Array[String],
          contact_id: String,
          first_message_at: Time?,
          last_message_at: Time?,
          message_count: Integer
        }

        type channel_score =
          { channel: String, fail_score: Integer, success_score: Integer }

        class ChannelScore < Sentdm::Internal::Type::BaseModel
          attr_reader channel: String?

          def channel=: (String) -> String

          attr_reader fail_score: Integer?

          def fail_score=: (Integer) -> Integer

          attr_reader success_score: Integer?

          def success_score=: (Integer) -> Integer

          def initialize: (
            ?channel: String,
            ?fail_score: Integer,
            ?success_score: Integer
          ) -> void

          def to_hash: -> {
            channel: String,
            fail_score: Integer,
            success_score: Integer
          }
        end
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
