module Sentdm
  module Models
    type destination_country = { id: String, is_main: bool }

    class DestinationCountry < Sentdm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader is_main: bool?

      def is_main=: (bool) -> bool

      def initialize: (?id: String, ?is_main: bool) -> void

      def to_hash: -> { id: String, is_main: bool }
    end
  end
end
