module Sentdm
  module Models
    type inbound_message_event_payload =
      {
        inbound_number: String,
        received_at: String,
        account_id: String,
        channel: String,
        media: ::Array[Sentdm::InboundMessageEventPayload::Media]?,
        message_id: String,
        outbound_number: String,
        text: String?,
        updated_at: String
      }

    class InboundMessageEventPayload < Sentdm::Internal::Type::BaseModel
      attr_accessor inbound_number: String

      attr_accessor received_at: String

      attr_reader account_id: String?

      def account_id=: (String) -> String

      attr_reader channel: String?

      def channel=: (String) -> String

      attr_accessor media: ::Array[Sentdm::InboundMessageEventPayload::Media]?

      attr_reader message_id: String?

      def message_id=: (String) -> String

      attr_reader outbound_number: String?

      def outbound_number=: (String) -> String

      attr_accessor text: String?

      attr_reader updated_at: String?

      def updated_at=: (String) -> String

      def initialize: (
        inbound_number: String,
        received_at: String,
        ?account_id: String,
        ?channel: String,
        ?media: ::Array[Sentdm::InboundMessageEventPayload::Media]?,
        ?message_id: String,
        ?outbound_number: String,
        ?text: String?,
        ?updated_at: String
      ) -> void

      def to_hash: -> {
        inbound_number: String,
        received_at: String,
        account_id: String,
        channel: String,
        media: ::Array[Sentdm::InboundMessageEventPayload::Media]?,
        message_id: String,
        outbound_number: String,
        text: String?,
        updated_at: String
      }

      type media =
        {
          :hash_sha256 => String?,
          mime_type: String?,
          size_bytes: Integer?,
          url: String?
        }

      class Media < Sentdm::Internal::Type::BaseModel
        attr_accessor hash_sha256: String?

        attr_accessor mime_type: String?

        attr_accessor size_bytes: Integer?

        attr_accessor url: String?

        def initialize: (
          ?hash_sha256: String?,
          ?mime_type: String?,
          ?size_bytes: Integer?,
          ?url: String?
        ) -> void

        def to_hash: -> {
          :hash_sha256 => String?,
          mime_type: String?,
          size_bytes: Integer?,
          url: String?
        }
      end
    end
  end
end
