module Sentdm
  module Models
    type me_retrieve_response =
      {
        data: Sentdm::Models::MeRetrieveResponse::Data?,
        error: Sentdm::Models::MeRetrieveResponse::Error?,
        meta: Sentdm::Models::MeRetrieveResponse::Meta,
        success: bool
      }

    class MeRetrieveResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::MeRetrieveResponse::Data?

      attr_accessor error: Sentdm::Models::MeRetrieveResponse::Error?

      attr_reader meta: Sentdm::Models::MeRetrieveResponse::Meta?

      def meta=: (
        Sentdm::Models::MeRetrieveResponse::Meta
      ) -> Sentdm::Models::MeRetrieveResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::MeRetrieveResponse::Data?,
        ?error: Sentdm::Models::MeRetrieveResponse::Error?,
        ?meta: Sentdm::Models::MeRetrieveResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::MeRetrieveResponse::Data?,
        error: Sentdm::Models::MeRetrieveResponse::Error?,
        meta: Sentdm::Models::MeRetrieveResponse::Meta,
        success: bool
      }

      type data =
        {
          id: String,
          channels: Sentdm::Models::MeRetrieveResponse::Data::Channels,
          created_at: Time,
          description: String?,
          email: String?,
          icon: String?,
          name: String,
          organization_id: String?,
          profiles: ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile],
          settings: Sentdm::Models::MeRetrieveResponse::Data::Settings?,
          short_name: String?,
          status: String?,
          type: String
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader channels: Sentdm::Models::MeRetrieveResponse::Data::Channels?

        def channels=: (
          Sentdm::Models::MeRetrieveResponse::Data::Channels
        ) -> Sentdm::Models::MeRetrieveResponse::Data::Channels

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_accessor description: String?

        attr_accessor email: String?

        attr_accessor icon: String?

        attr_reader name: String?

        def name=: (String) -> String

        attr_accessor organization_id: String?

        attr_reader profiles: ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile]?

        def profiles=: (
          ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile]
        ) -> ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile]

        attr_accessor settings: Sentdm::Models::MeRetrieveResponse::Data::Settings?

        attr_accessor short_name: String?

        attr_accessor status: String?

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?id: String,
          ?channels: Sentdm::Models::MeRetrieveResponse::Data::Channels,
          ?created_at: Time,
          ?description: String?,
          ?email: String?,
          ?icon: String?,
          ?name: String,
          ?organization_id: String?,
          ?profiles: ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile],
          ?settings: Sentdm::Models::MeRetrieveResponse::Data::Settings?,
          ?short_name: String?,
          ?status: String?,
          ?type: String
        ) -> void

        def to_hash: -> {
          id: String,
          channels: Sentdm::Models::MeRetrieveResponse::Data::Channels,
          created_at: Time,
          description: String?,
          email: String?,
          icon: String?,
          name: String,
          organization_id: String?,
          profiles: ::Array[Sentdm::Models::MeRetrieveResponse::Data::Profile],
          settings: Sentdm::Models::MeRetrieveResponse::Data::Settings?,
          short_name: String?,
          status: String?,
          type: String
        }

        type channels =
          {
            rcs: Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs,
            sms: Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS,
            whatsapp: Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp
          }

        class Channels < Sentdm::Internal::Type::BaseModel
          attr_reader rcs: Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs?

          def rcs=: (
            Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs
          ) -> Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs

          attr_reader sms: Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS?

          def sms=: (
            Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS
          ) -> Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS

          attr_reader whatsapp: Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp?

          def whatsapp=: (
            Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp
          ) -> Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp

          def initialize: (
            ?rcs: Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs,
            ?sms: Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS,
            ?whatsapp: Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp
          ) -> void

          def to_hash: -> {
            rcs: Sentdm::Models::MeRetrieveResponse::Data::Channels::Rcs,
            sms: Sentdm::Models::MeRetrieveResponse::Data::Channels::SMS,
            whatsapp: Sentdm::Models::MeRetrieveResponse::Data::Channels::Whatsapp
          }

          type rcs = { configured: bool, phone_number: String? }

          class Rcs < Sentdm::Internal::Type::BaseModel
            attr_reader configured: bool?

            def configured=: (bool) -> bool

            attr_accessor phone_number: String?

            def initialize: (?configured: bool, ?phone_number: String?) -> void

            def to_hash: -> { configured: bool, phone_number: String? }
          end

          type sms = { configured: bool, phone_number: String? }

          class SMS < Sentdm::Internal::Type::BaseModel
            attr_reader configured: bool?

            def configured=: (bool) -> bool

            attr_accessor phone_number: String?

            def initialize: (?configured: bool, ?phone_number: String?) -> void

            def to_hash: -> { configured: bool, phone_number: String? }
          end

          type whatsapp =
            { business_name: String?, configured: bool, phone_number: String? }

          class Whatsapp < Sentdm::Internal::Type::BaseModel
            attr_accessor business_name: String?

            attr_reader configured: bool?

            def configured=: (bool) -> bool

            attr_accessor phone_number: String?

            def initialize: (
              ?business_name: String?,
              ?configured: bool,
              ?phone_number: String?
            ) -> void

            def to_hash: -> {
              business_name: String?,
              configured: bool,
              phone_number: String?
            }
          end
        end

        type profile =
          {
            id: String,
            created_at: Time,
            description: String?,
            icon: String?,
            name: String,
            role: String?,
            settings: Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings,
            short_name: String?,
            status: String?
          }

        class Profile < Sentdm::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_accessor description: String?

          attr_accessor icon: String?

          attr_reader name: String?

          def name=: (String) -> String

          attr_accessor role: String?

          attr_reader settings: Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings?

          def settings=: (
            Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings
          ) -> Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings

          attr_accessor short_name: String?

          attr_accessor status: String?

          def initialize: (
            ?id: String,
            ?created_at: Time,
            ?description: String?,
            ?icon: String?,
            ?name: String,
            ?role: String?,
            ?settings: Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings,
            ?short_name: String?,
            ?status: String?
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Time,
            description: String?,
            icon: String?,
            name: String,
            role: String?,
            settings: Sentdm::Models::MeRetrieveResponse::Data::Profile::Settings,
            short_name: String?,
            status: String?
          }

          type settings =
            {
              allow_contact_sharing: bool?,
              allow_template_sharing: bool?,
              billing_model: String?,
              inherit_contacts: bool?,
              inherit_tcr_brand: bool?,
              inherit_tcr_campaign: bool?,
              inherit_templates: bool?
            }

          class Settings < Sentdm::Internal::Type::BaseModel
            attr_accessor allow_contact_sharing: bool?

            attr_accessor allow_template_sharing: bool?

            attr_accessor billing_model: String?

            attr_accessor inherit_contacts: bool?

            attr_accessor inherit_tcr_brand: bool?

            attr_accessor inherit_tcr_campaign: bool?

            attr_accessor inherit_templates: bool?

            def initialize: (
              ?allow_contact_sharing: bool?,
              ?allow_template_sharing: bool?,
              ?billing_model: String?,
              ?inherit_contacts: bool?,
              ?inherit_tcr_brand: bool?,
              ?inherit_tcr_campaign: bool?,
              ?inherit_templates: bool?
            ) -> void

            def to_hash: -> {
              allow_contact_sharing: bool?,
              allow_template_sharing: bool?,
              billing_model: String?,
              inherit_contacts: bool?,
              inherit_tcr_brand: bool?,
              inherit_tcr_campaign: bool?,
              inherit_templates: bool?
            }
          end
        end

        type settings =
          {
            allow_contact_sharing: bool?,
            allow_template_sharing: bool?,
            billing_model: String?,
            inherit_contacts: bool?,
            inherit_tcr_brand: bool?,
            inherit_tcr_campaign: bool?,
            inherit_templates: bool?
          }

        class Settings < Sentdm::Internal::Type::BaseModel
          attr_accessor allow_contact_sharing: bool?

          attr_accessor allow_template_sharing: bool?

          attr_accessor billing_model: String?

          attr_accessor inherit_contacts: bool?

          attr_accessor inherit_tcr_brand: bool?

          attr_accessor inherit_tcr_campaign: bool?

          attr_accessor inherit_templates: bool?

          def initialize: (
            ?allow_contact_sharing: bool?,
            ?allow_template_sharing: bool?,
            ?billing_model: String?,
            ?inherit_contacts: bool?,
            ?inherit_tcr_brand: bool?,
            ?inherit_tcr_campaign: bool?,
            ?inherit_templates: bool?
          ) -> void

          def to_hash: -> {
            allow_contact_sharing: bool?,
            allow_template_sharing: bool?,
            billing_model: String?,
            inherit_contacts: bool?,
            inherit_tcr_brand: bool?,
            inherit_tcr_campaign: bool?,
            inherit_templates: bool?
          }
        end
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
