module Sentdm
  module Models
    type message_retrieve_activities_response =
      {
        data: Sentdm::Models::MessageRetrieveActivitiesResponse::Data?,
        error: Sentdm::Models::MessageRetrieveActivitiesResponse::Error?,
        meta: Sentdm::Models::MessageRetrieveActivitiesResponse::Meta,
        success: bool
      }

    class MessageRetrieveActivitiesResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::MessageRetrieveActivitiesResponse::Data?

      attr_accessor error: Sentdm::Models::MessageRetrieveActivitiesResponse::Error?

      attr_reader meta: Sentdm::Models::MessageRetrieveActivitiesResponse::Meta?

      def meta=: (
        Sentdm::Models::MessageRetrieveActivitiesResponse::Meta
      ) -> Sentdm::Models::MessageRetrieveActivitiesResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::MessageRetrieveActivitiesResponse::Data?,
        ?error: Sentdm::Models::MessageRetrieveActivitiesResponse::Error?,
        ?meta: Sentdm::Models::MessageRetrieveActivitiesResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::MessageRetrieveActivitiesResponse::Data?,
        error: Sentdm::Models::MessageRetrieveActivitiesResponse::Error?,
        meta: Sentdm::Models::MessageRetrieveActivitiesResponse::Meta,
        success: bool
      }

      type data =
        {
          activities: ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          message_id: String
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader activities: ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity]?

        def activities=: (
          ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity]
        ) -> ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity]

        attr_reader message_id: String?

        def message_id=: (String) -> String

        def initialize: (
          ?activities: ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          ?message_id: String
        ) -> void

        def to_hash: -> {
          activities: ::Array[Sentdm::Models::MessageRetrieveActivitiesResponse::Data::Activity],
          message_id: String
        }

        type activity =
          {
            active_contact_price: String?,
            description: String,
            from: String?,
            price: String?,
            status: String,
            timestamp: Time
          }

        class Activity < Sentdm::Internal::Type::BaseModel
          attr_accessor active_contact_price: String?

          attr_reader description: String?

          def description=: (String) -> String

          attr_accessor from: String?

          attr_accessor price: String?

          attr_reader status: String?

          def status=: (String) -> String

          attr_reader timestamp: Time?

          def timestamp=: (Time) -> Time

          def initialize: (
            ?active_contact_price: String?,
            ?description: String,
            ?from: String?,
            ?price: String?,
            ?status: String,
            ?timestamp: Time
          ) -> void

          def to_hash: -> {
            active_contact_price: String?,
            description: String,
            from: String?,
            price: String?,
            status: String,
            timestamp: Time
          }
        end
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
