module Sentdm
  module Models
    type message_send_quick_message_params =
      { custom_message: String, phone_number: String }
      & Sentdm::Internal::Type::request_parameters

    class MessageSendQuickMessageParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor custom_message: String

      attr_accessor phone_number: String

      def initialize: (
        custom_message: String,
        phone_number: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        custom_message: String,
        phone_number: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
