module Sentdm
  module Models
    type message_send_response =
      {
        data: Sentdm::Models::MessageSendResponse::Data?,
        error: Sentdm::Models::MessageSendResponse::Error?,
        meta: Sentdm::Models::MessageSendResponse::Meta,
        success: bool
      }

    class MessageSendResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::MessageSendResponse::Data?

      attr_accessor error: Sentdm::Models::MessageSendResponse::Error?

      attr_reader meta: Sentdm::Models::MessageSendResponse::Meta?

      def meta=: (
        Sentdm::Models::MessageSendResponse::Meta
      ) -> Sentdm::Models::MessageSendResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::MessageSendResponse::Data?,
        ?error: Sentdm::Models::MessageSendResponse::Error?,
        ?meta: Sentdm::Models::MessageSendResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::MessageSendResponse::Data?,
        error: Sentdm::Models::MessageSendResponse::Error?,
        meta: Sentdm::Models::MessageSendResponse::Meta,
        success: bool
      }

      type data =
        {
          recipients: ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient],
          status: String,
          template_id: String,
          template_name: String
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader recipients: ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient]?

        def recipients=: (
          ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient]
        ) -> ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient]

        attr_reader status: String?

        def status=: (String) -> String

        attr_reader template_id: String?

        def template_id=: (String) -> String

        attr_reader template_name: String?

        def template_name=: (String) -> String

        def initialize: (
          ?recipients: ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient],
          ?status: String,
          ?template_id: String,
          ?template_name: String
        ) -> void

        def to_hash: -> {
          recipients: ::Array[Sentdm::Models::MessageSendResponse::Data::Recipient],
          status: String,
          template_id: String,
          template_name: String
        }

        type recipient =
          { body: String?, channel: String?, message_id: String, to: String }

        class Recipient < Sentdm::Internal::Type::BaseModel
          attr_accessor body: String?

          attr_accessor channel: String?

          attr_reader message_id: String?

          def message_id=: (String) -> String

          attr_reader to: String?

          def to=: (String) -> String

          def initialize: (
            ?body: String?,
            ?channel: String?,
            ?message_id: String,
            ?to: String
          ) -> void

          def to_hash: -> {
            body: String?,
            channel: String?,
            message_id: String,
            to: String
          }
        end
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
