module Sentdm
  module Models
    type message_event =
      {
        event: String?,
        field: String,
        payload: Sentdm::MessageEventPayload?,
        request_id: String?,
        timestamp: String
      }

    class MessageEvent < Sentdm::Internal::Type::BaseModel
      attr_accessor event: String?

      attr_reader field: String?

      def field=: (String) -> String

      attr_accessor payload: Sentdm::MessageEventPayload?

      attr_accessor request_id: String?

      attr_reader timestamp: String?

      def timestamp=: (String) -> String

      def initialize: (
        ?event: String?,
        ?field: String,
        ?payload: Sentdm::MessageEventPayload?,
        ?request_id: String?,
        ?timestamp: String
      ) -> void

      def to_hash: -> {
        event: String?,
        field: String,
        payload: Sentdm::MessageEventPayload?,
        request_id: String?,
        timestamp: String
      }
    end
  end
end
