module Sentdm
  module Models
    type message_send_to_phone_params =
      {
        phone_number: String,
        template_id: String,
        template_variables: ::Hash[Symbol, String]?
      }
      & Sentdm::Internal::Type::request_parameters

    class MessageSendToPhoneParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor phone_number: String

      attr_accessor template_id: String

      attr_accessor template_variables: ::Hash[Symbol, String]?

      def initialize: (
        phone_number: String,
        template_id: String,
        ?template_variables: ::Hash[Symbol, String]?,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        phone_number: String,
        template_id: String,
        template_variables: ::Hash[Symbol, String]?,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
