module Sentdm
  module Models
    type message_retrieve_response =
      {
        id: String,
        channel: String,
        contact_id: String,
        corrected_price: Float?,
        created_at: Time,
        customer_id: String,
        events: ::Array[Sentdm::Models::MessageRetrieveResponse::Event]?,
        message_body: Sentdm::Models::MessageRetrieveResponse::MessageBody?,
        phone_number: String,
        phone_number_international: String,
        region_code: String,
        status: String,
        template_category: String,
        template_id: String?,
        template_name: String
      }

    class MessageRetrieveResponse < Sentdm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader channel: String?

      def channel=: (String) -> String

      attr_reader contact_id: String?

      def contact_id=: (String) -> String

      attr_accessor corrected_price: Float?

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader customer_id: String?

      def customer_id=: (String) -> String

      attr_accessor events: ::Array[Sentdm::Models::MessageRetrieveResponse::Event]?

      attr_accessor message_body: Sentdm::Models::MessageRetrieveResponse::MessageBody?

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader phone_number_international: String?

      def phone_number_international=: (String) -> String

      attr_reader region_code: String?

      def region_code=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader template_category: String?

      def template_category=: (String) -> String

      attr_accessor template_id: String?

      attr_reader template_name: String?

      def template_name=: (String) -> String

      def initialize: (
        ?id: String,
        ?channel: String,
        ?contact_id: String,
        ?corrected_price: Float?,
        ?created_at: Time,
        ?customer_id: String,
        ?events: ::Array[Sentdm::Models::MessageRetrieveResponse::Event]?,
        ?message_body: Sentdm::Models::MessageRetrieveResponse::MessageBody?,
        ?phone_number: String,
        ?phone_number_international: String,
        ?region_code: String,
        ?status: String,
        ?template_category: String,
        ?template_id: String?,
        ?template_name: String
      ) -> void

      def to_hash: -> {
        id: String,
        channel: String,
        contact_id: String,
        corrected_price: Float?,
        created_at: Time,
        customer_id: String,
        events: ::Array[Sentdm::Models::MessageRetrieveResponse::Event]?,
        message_body: Sentdm::Models::MessageRetrieveResponse::MessageBody?,
        phone_number: String,
        phone_number_international: String,
        region_code: String,
        status: String,
        template_category: String,
        template_id: String?,
        template_name: String
      }

      type event = { description: String?, status: String, timestamp: Time }

      class Event < Sentdm::Internal::Type::BaseModel
        attr_accessor description: String?

        attr_reader status: String?

        def status=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        def initialize: (
          ?description: String?,
          ?status: String,
          ?timestamp: Time
        ) -> void

        def to_hash: -> {
          description: String?,
          status: String,
          timestamp: Time
        }
      end

      type message_body =
        {
          buttons: ::Array[Sentdm::Models::MessageRetrieveResponse::MessageBody::Button]?,
          content: String,
          footer: String?,
          header: String?
        }

      class MessageBody < Sentdm::Internal::Type::BaseModel
        attr_accessor buttons: ::Array[Sentdm::Models::MessageRetrieveResponse::MessageBody::Button]?

        attr_reader content: String?

        def content=: (String) -> String

        attr_accessor footer: String?

        attr_accessor header: String?

        def initialize: (
          ?buttons: ::Array[Sentdm::Models::MessageRetrieveResponse::MessageBody::Button]?,
          ?content: String,
          ?footer: String?,
          ?header: String?
        ) -> void

        def to_hash: -> {
          buttons: ::Array[Sentdm::Models::MessageRetrieveResponse::MessageBody::Button]?,
          content: String,
          footer: String?,
          header: String?
        }

        type button = { type: String, value: String }

        class Button < Sentdm::Internal::Type::BaseModel
          attr_reader type: String?

          def type=: (String) -> String

          attr_reader value: String?

          def value=: (String) -> String

          def initialize: (?type: String, ?value: String) -> void

          def to_hash: -> { type: String, value: String }
        end
      end
    end
  end
end
