module Sentdm
  module Models
    type message_send_params =
      {
        channel: ::Array[String]?,
        template: Sentdm::MessageSendParams::Template,
        test_mode: bool,
        to: ::Array[String],
        idempotency_key: String
      }
      & Sentdm::Internal::Type::request_parameters

    class MessageSendParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor channel: ::Array[String]?

      attr_reader template: Sentdm::MessageSendParams::Template?

      def template=: (
        Sentdm::MessageSendParams::Template
      ) -> Sentdm::MessageSendParams::Template

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader to: ::Array[String]?

      def to=: (::Array[String]) -> ::Array[String]

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?channel: ::Array[String]?,
        ?template: Sentdm::MessageSendParams::Template,
        ?test_mode: bool,
        ?to: ::Array[String],
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        channel: ::Array[String]?,
        template: Sentdm::MessageSendParams::Template,
        test_mode: bool,
        to: ::Array[String],
        idempotency_key: String,
        request_options: Sentdm::RequestOptions
      }

      type template =
        { id: String?, name: String?, parameters: ::Hash[Symbol, String]? }

      class Template < Sentdm::Internal::Type::BaseModel
        attr_accessor id: String?

        attr_accessor name: String?

        attr_accessor parameters: ::Hash[Symbol, String]?

        def initialize: (
          ?id: String?,
          ?name: String?,
          ?parameters: ::Hash[Symbol, String]?
        ) -> void

        def to_hash: -> {
          id: String?,
          name: String?,
          parameters: ::Hash[Symbol, String]?
        }
      end
    end
  end
end
