module Sentdm
  module Models
    type mutation_request_base = { sandbox: bool }

    class MutationRequestBase < Sentdm::Internal::Type::BaseModel
      attr_reader sandbox: bool?

      def sandbox=: (bool) -> bool

      def initialize: (?sandbox: bool) -> void

      def to_hash: -> { sandbox: bool }
    end
  end
end
