module Sentdm
  module Models
    type number_lookup_response =
      {
        data: Sentdm::Models::NumberLookupResponse::Data?,
        error: Sentdm::Models::NumberLookupResponse::Error?,
        meta: Sentdm::Models::NumberLookupResponse::Meta,
        success: bool
      }

    class NumberLookupResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::NumberLookupResponse::Data?

      attr_accessor error: Sentdm::Models::NumberLookupResponse::Error?

      attr_reader meta: Sentdm::Models::NumberLookupResponse::Meta?

      def meta=: (
        Sentdm::Models::NumberLookupResponse::Meta
      ) -> Sentdm::Models::NumberLookupResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::NumberLookupResponse::Data?,
        ?error: Sentdm::Models::NumberLookupResponse::Error?,
        ?meta: Sentdm::Models::NumberLookupResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::NumberLookupResponse::Data?,
        error: Sentdm::Models::NumberLookupResponse::Error?,
        meta: Sentdm::Models::NumberLookupResponse::Meta,
        success: bool
      }

      type data =
        {
          carrier_name: String?,
          country_code: String?,
          is_ported: bool?,
          is_valid: bool,
          is_voip: bool?,
          line_type: String?,
          mobile_country_code: String?,
          mobile_network_code: String?,
          phone_number: String
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_accessor carrier_name: String?

        attr_accessor country_code: String?

        attr_accessor is_ported: bool?

        attr_reader is_valid: bool?

        def is_valid=: (bool) -> bool

        attr_accessor is_voip: bool?

        attr_accessor line_type: String?

        attr_accessor mobile_country_code: String?

        attr_accessor mobile_network_code: String?

        attr_reader phone_number: String?

        def phone_number=: (String) -> String

        def initialize: (
          ?carrier_name: String?,
          ?country_code: String?,
          ?is_ported: bool?,
          ?is_valid: bool,
          ?is_voip: bool?,
          ?line_type: String?,
          ?mobile_country_code: String?,
          ?mobile_network_code: String?,
          ?phone_number: String
        ) -> void

        def to_hash: -> {
          carrier_name: String?,
          country_code: String?,
          is_ported: bool?,
          is_valid: bool,
          is_voip: bool?,
          line_type: String?,
          mobile_country_code: String?,
          mobile_network_code: String?,
          phone_number: String
        }
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
