module Sentdm
  module Models
    type organization_retrieve_profiles_params =
      {  } & Sentdm::Internal::Type::request_parameters

    class OrganizationRetrieveProfilesParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      def initialize: (?request_options: Sentdm::request_opts) -> void

      def to_hash: -> { request_options: Sentdm::RequestOptions }
    end
  end
end
