module Sentdm
  module Models
    type profile_create_params =
      {
        allow_contact_sharing: bool,
        allow_template_sharing: bool,
        billing_model: String?,
        description: String?,
        icon: String?,
        inherit_contacts: bool?,
        inherit_tcr_brand: bool?,
        inherit_tcr_campaign: bool?,
        inherit_templates: bool?,
        name: String,
        short_name: String?,
        test_mode: bool,
        idempotency_key: String
      }
      & Sentdm::Internal::Type::request_parameters

    class ProfileCreateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_reader allow_contact_sharing: bool?

      def allow_contact_sharing=: (bool) -> bool

      attr_reader allow_template_sharing: bool?

      def allow_template_sharing=: (bool) -> bool

      attr_accessor billing_model: String?

      attr_accessor description: String?

      attr_accessor icon: String?

      attr_accessor inherit_contacts: bool?

      attr_accessor inherit_tcr_brand: bool?

      attr_accessor inherit_tcr_campaign: bool?

      attr_accessor inherit_templates: bool?

      attr_reader name: String?

      def name=: (String) -> String

      attr_accessor short_name: String?

      attr_reader test_mode: bool?

      def test_mode=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      def initialize: (
        ?allow_contact_sharing: bool,
        ?allow_template_sharing: bool,
        ?billing_model: String?,
        ?description: String?,
        ?icon: String?,
        ?inherit_contacts: bool?,
        ?inherit_tcr_brand: bool?,
        ?inherit_tcr_campaign: bool?,
        ?inherit_templates: bool?,
        ?name: String,
        ?short_name: String?,
        ?test_mode: bool,
        ?idempotency_key: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        allow_contact_sharing: bool,
        allow_template_sharing: bool,
        billing_model: String?,
        description: String?,
        icon: String?,
        inherit_contacts: bool?,
        inherit_tcr_brand: bool?,
        inherit_tcr_campaign: bool?,
        inherit_templates: bool?,
        name: String,
        short_name: String?,
        test_mode: bool,
        idempotency_key: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
