module Sentdm
  module Models
    type sent_dm_services_endpoints_customer_ap_iv3_contracts_requests_brands_brand_contact_info =
      {
        name: String,
        business_name: String?,
        email: String?,
        phone: String?,
        phone_country_code: String?,
        role: String?
      }

    class SentDmServicesEndpointsCustomerApIv3ContractsRequestsBrandsBrandContactInfo < Sentdm::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor business_name: String?

      attr_accessor email: String?

      attr_accessor phone: String?

      attr_accessor phone_country_code: String?

      attr_accessor role: String?

      def initialize: (
        name: String,
        ?business_name: String?,
        ?email: String?,
        ?phone: String?,
        ?phone_country_code: String?,
        ?role: String?
      ) -> void

      def to_hash: -> {
        name: String,
        business_name: String?,
        email: String?,
        phone: String?,
        phone_country_code: String?,
        role: String?
      }
    end
  end
end
