module Sentdm
  module Models
    type sent_dm_services_endpoints_customer_ap_iv3_contracts_requests_brands_brand_compliance_info =
      {
        brand_relationship: Sentdm::Models::tcr_brand_relationship,
        vertical: Sentdm::Models::tcr_vertical,
        destination_countries: ::Array[Sentdm::DestinationCountry]?,
        expected_messaging_volume: String?,
        is_tcr_application: bool?,
        notes: String?,
        phone_number_prefix: String?,
        primary_use_case: String?
      }

    class SentDmServicesEndpointsCustomerApIv3ContractsRequestsBrandsBrandComplianceInfo < Sentdm::Internal::Type::BaseModel
      attr_accessor brand_relationship: Sentdm::Models::tcr_brand_relationship

      attr_accessor vertical: Sentdm::Models::tcr_vertical

      attr_accessor destination_countries: ::Array[Sentdm::DestinationCountry]?

      attr_accessor expected_messaging_volume: String?

      attr_accessor is_tcr_application: bool?

      attr_accessor notes: String?

      attr_accessor phone_number_prefix: String?

      attr_accessor primary_use_case: String?

      def initialize: (
        brand_relationship: Sentdm::Models::tcr_brand_relationship,
        vertical: Sentdm::Models::tcr_vertical,
        ?destination_countries: ::Array[Sentdm::DestinationCountry]?,
        ?expected_messaging_volume: String?,
        ?is_tcr_application: bool?,
        ?notes: String?,
        ?phone_number_prefix: String?,
        ?primary_use_case: String?
      ) -> void

      def to_hash: -> {
        brand_relationship: Sentdm::Models::tcr_brand_relationship,
        vertical: Sentdm::Models::tcr_vertical,
        destination_countries: ::Array[Sentdm::DestinationCountry]?,
        expected_messaging_volume: String?,
        is_tcr_application: bool?,
        notes: String?,
        phone_number_prefix: String?,
        primary_use_case: String?
      }
    end
  end
end
