module Sentdm
  module Models
    type sent_dm_services_common_contracts_poc_os_template_button =
      {
        props: Sentdm::SentDmServicesCommonContractsPocOsTemplateButtonProps,
        type: String,
        id: Integer
      }

    class SentDmServicesCommonContractsPocOsTemplateButton < Sentdm::Internal::Type::BaseModel
      attr_accessor props: Sentdm::SentDmServicesCommonContractsPocOsTemplateButtonProps

      attr_accessor type: String

      attr_reader id: Integer?

      def id=: (Integer) -> Integer

      def initialize: (
        props: Sentdm::SentDmServicesCommonContractsPocOsTemplateButtonProps,
        type: String,
        ?id: Integer
      ) -> void

      def to_hash: -> {
        props: Sentdm::SentDmServicesCommonContractsPocOsTemplateButtonProps,
        type: String,
        id: Integer
      }
    end
  end
end
