module Sentdm
  module Models
    type template_definition =
      {
        body: Sentdm::TemplateBody,
        authentication_config: Sentdm::AuthenticationConfig?,
        buttons: ::Array[Sentdm::TemplateButton]?,
        definition_version: String?,
        footer: Sentdm::TemplateFooter?,
        header: Sentdm::TemplateHeader?
      }

    class TemplateDefinition < Sentdm::Internal::Type::BaseModel
      attr_accessor body: Sentdm::TemplateBody

      attr_accessor authentication_config: Sentdm::AuthenticationConfig?

      attr_accessor buttons: ::Array[Sentdm::TemplateButton]?

      attr_accessor definition_version: String?

      attr_accessor footer: Sentdm::TemplateFooter?

      attr_accessor header: Sentdm::TemplateHeader?

      def initialize: (
        body: Sentdm::TemplateBody,
        ?authentication_config: Sentdm::AuthenticationConfig?,
        ?buttons: ::Array[Sentdm::TemplateButton]?,
        ?definition_version: String?,
        ?footer: Sentdm::TemplateFooter?,
        ?header: Sentdm::TemplateHeader?
      ) -> void

      def to_hash: -> {
        body: Sentdm::TemplateBody,
        authentication_config: Sentdm::AuthenticationConfig?,
        buttons: ::Array[Sentdm::TemplateButton]?,
        definition_version: String?,
        footer: Sentdm::TemplateFooter?,
        header: Sentdm::TemplateHeader?
      }
    end
  end
end
