module Sentdm
  module Models
    type template_create_response =
      {
        data: Sentdm::Models::TemplateCreateResponse::Data?,
        error: Sentdm::Models::TemplateCreateResponse::Error?,
        meta: Sentdm::Models::TemplateCreateResponse::Meta,
        success: bool
      }

    class TemplateCreateResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::TemplateCreateResponse::Data?

      attr_accessor error: Sentdm::Models::TemplateCreateResponse::Error?

      attr_reader meta: Sentdm::Models::TemplateCreateResponse::Meta?

      def meta=: (
        Sentdm::Models::TemplateCreateResponse::Meta
      ) -> Sentdm::Models::TemplateCreateResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::TemplateCreateResponse::Data?,
        ?error: Sentdm::Models::TemplateCreateResponse::Error?,
        ?meta: Sentdm::Models::TemplateCreateResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::TemplateCreateResponse::Data?,
        error: Sentdm::Models::TemplateCreateResponse::Error?,
        meta: Sentdm::Models::TemplateCreateResponse::Meta,
        success: bool
      }

      type data =
        {
          id: String,
          category: String,
          channels: ::Array[String]?,
          created_at: Time,
          is_published: bool,
          language: String,
          name: String,
          status: String,
          updated_at: Time?,
          variables: ::Array[String]?
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader category: String?

        def category=: (String) -> String

        attr_accessor channels: ::Array[String]?

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader is_published: bool?

        def is_published=: (bool) -> bool

        attr_reader language: String?

        def language=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        attr_accessor updated_at: Time?

        attr_accessor variables: ::Array[String]?

        def initialize: (
          ?id: String,
          ?category: String,
          ?channels: ::Array[String]?,
          ?created_at: Time,
          ?is_published: bool,
          ?language: String,
          ?name: String,
          ?status: String,
          ?updated_at: Time?,
          ?variables: ::Array[String]?
        ) -> void

        def to_hash: -> {
          id: String,
          category: String,
          channels: ::Array[String]?,
          created_at: Time,
          is_published: bool,
          language: String,
          name: String,
          status: String,
          updated_at: Time?,
          variables: ::Array[String]?
        }
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
