module Sentdm
  module Models
    type template_delete_params =
      {
        id: String,
        delete_from_meta: bool?,
        sandbox: bool,
        x_profile_id: String
      }
      & Sentdm::Internal::Type::request_parameters

    class TemplateDeleteParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor delete_from_meta: bool?

      attr_reader sandbox: bool?

      def sandbox=: (bool) -> bool

      attr_reader x_profile_id: String?

      def x_profile_id=: (String) -> String

      def initialize: (
        id: String,
        ?delete_from_meta: bool?,
        ?sandbox: bool,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        delete_from_meta: bool?,
        sandbox: bool,
        x_profile_id: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
