module Sentdm
  module Models
    type template_create_params =
      {
        definition: Sentdm::TemplateDefinition,
        category: String?,
        language: String?,
        submit_for_review: bool
      }
      & Sentdm::Internal::Type::request_parameters

    class TemplateCreateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor definition: Sentdm::TemplateDefinition

      attr_accessor category: String?

      attr_accessor language: String?

      attr_reader submit_for_review: bool?

      def submit_for_review=: (bool) -> bool

      def initialize: (
        definition: Sentdm::TemplateDefinition,
        ?category: String?,
        ?language: String?,
        ?submit_for_review: bool,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        definition: Sentdm::TemplateDefinition,
        category: String?,
        language: String?,
        submit_for_review: bool,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
