module Sentdm
  module Models
    type template_update_params =
      {
        id: String,
        category: String?,
        definition: Sentdm::TemplateUpdateParams::Definition?,
        language: String?,
        name: String?,
        sandbox: bool,
        submit_for_review: bool,
        idempotency_key: String,
        x_profile_id: String
      }
      & Sentdm::Internal::Type::request_parameters

    class TemplateUpdateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor category: String?

      attr_accessor definition: Sentdm::TemplateUpdateParams::Definition?

      attr_accessor language: String?

      attr_accessor name: String?

      attr_reader sandbox: bool?

      def sandbox=: (bool) -> bool

      attr_reader submit_for_review: bool?

      def submit_for_review=: (bool) -> bool

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader x_profile_id: String?

      def x_profile_id=: (String) -> String

      def initialize: (
        id: String,
        ?category: String?,
        ?definition: Sentdm::TemplateUpdateParams::Definition?,
        ?language: String?,
        ?name: String?,
        ?sandbox: bool,
        ?submit_for_review: bool,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        category: String?,
        definition: Sentdm::TemplateUpdateParams::Definition?,
        language: String?,
        name: String?,
        sandbox: bool,
        submit_for_review: bool,
        idempotency_key: String,
        x_profile_id: String,
        request_options: Sentdm::RequestOptions
      }

      type definition =
        {
          body: Sentdm::TemplateUpdateParams::Definition::Body,
          authentication_config: Sentdm::TemplateUpdateParams::Definition::AuthenticationConfig?,
          buttons: ::Array[Sentdm::TemplateUpdateParams::Definition::Button]?,
          definition_version: String?,
          footer: Sentdm::TemplateUpdateParams::Definition::Footer?,
          header: Sentdm::TemplateUpdateParams::Definition::Header?
        }

      class Definition < Sentdm::Internal::Type::BaseModel
        attr_accessor body: Sentdm::TemplateUpdateParams::Definition::Body

        attr_accessor authentication_config: Sentdm::TemplateUpdateParams::Definition::AuthenticationConfig?

        attr_accessor buttons: ::Array[Sentdm::TemplateUpdateParams::Definition::Button]?

        attr_accessor definition_version: String?

        attr_accessor footer: Sentdm::TemplateUpdateParams::Definition::Footer?

        attr_accessor header: Sentdm::TemplateUpdateParams::Definition::Header?

        def initialize: (
          body: Sentdm::TemplateUpdateParams::Definition::Body,
          ?authentication_config: Sentdm::TemplateUpdateParams::Definition::AuthenticationConfig?,
          ?buttons: ::Array[Sentdm::TemplateUpdateParams::Definition::Button]?,
          ?definition_version: String?,
          ?footer: Sentdm::TemplateUpdateParams::Definition::Footer?,
          ?header: Sentdm::TemplateUpdateParams::Definition::Header?
        ) -> void

        def to_hash: -> {
          body: Sentdm::TemplateUpdateParams::Definition::Body,
          authentication_config: Sentdm::TemplateUpdateParams::Definition::AuthenticationConfig?,
          buttons: ::Array[Sentdm::TemplateUpdateParams::Definition::Button]?,
          definition_version: String?,
          footer: Sentdm::TemplateUpdateParams::Definition::Footer?,
          header: Sentdm::TemplateUpdateParams::Definition::Header?
        }

        type body =
          {
            multi_channel: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel?,
            rcs: Sentdm::TemplateUpdateParams::Definition::Body::Rcs?,
            sms: Sentdm::TemplateUpdateParams::Definition::Body::SMS?,
            whatsapp: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp?
          }

        class Body < Sentdm::Internal::Type::BaseModel
          attr_accessor multi_channel: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel?

          attr_accessor rcs: Sentdm::TemplateUpdateParams::Definition::Body::Rcs?

          attr_accessor sms: Sentdm::TemplateUpdateParams::Definition::Body::SMS?

          attr_accessor whatsapp: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp?

          def initialize: (
            ?multi_channel: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel?,
            ?rcs: Sentdm::TemplateUpdateParams::Definition::Body::Rcs?,
            ?sms: Sentdm::TemplateUpdateParams::Definition::Body::SMS?,
            ?whatsapp: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp?
          ) -> void

          def to_hash: -> {
            multi_channel: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel?,
            rcs: Sentdm::TemplateUpdateParams::Definition::Body::Rcs?,
            sms: Sentdm::TemplateUpdateParams::Definition::Body::SMS?,
            whatsapp: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp?
          }

          type multi_channel =
            {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable]?
            }

          class MultiChannel < Sentdm::Internal::Type::BaseModel
            attr_accessor template: String

            attr_accessor type: String?

            attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable]?

            def initialize: (
              template: String,
              ?type: String?,
              ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable]?
            ) -> void

            def to_hash: -> {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable]?
            }

            type variable =
              {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable::Props,
                type: String,
                id: Integer
              }

            class Variable < Sentdm::Internal::Type::BaseModel
              attr_accessor name: String

              attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable::Props

              attr_accessor type: String

              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              def initialize: (
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable::Props,
                type: String,
                ?id: Integer
              ) -> void

              def to_hash: -> {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::MultiChannel::Variable::Props,
                type: String,
                id: Integer
              }

              type props =
                {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }

              class Props < Sentdm::Internal::Type::BaseModel
                attr_accessor media_type: String

                attr_accessor sample: String

                attr_accessor url: String

                attr_accessor variable_type: String

                attr_accessor alt: String?

                attr_accessor regex: String?

                attr_accessor short_url: String?

                def initialize: (
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  ?alt: String?,
                  ?regex: String?,
                  ?short_url: String?
                ) -> void

                def to_hash: -> {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }
              end
            end
          end

          type rcs =
            {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable]?
            }

          class Rcs < Sentdm::Internal::Type::BaseModel
            attr_accessor template: String

            attr_accessor type: String?

            attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable]?

            def initialize: (
              template: String,
              ?type: String?,
              ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable]?
            ) -> void

            def to_hash: -> {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable]?
            }

            type variable =
              {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable::Props,
                type: String,
                id: Integer
              }

            class Variable < Sentdm::Internal::Type::BaseModel
              attr_accessor name: String

              attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable::Props

              attr_accessor type: String

              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              def initialize: (
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable::Props,
                type: String,
                ?id: Integer
              ) -> void

              def to_hash: -> {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Rcs::Variable::Props,
                type: String,
                id: Integer
              }

              type props =
                {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }

              class Props < Sentdm::Internal::Type::BaseModel
                attr_accessor media_type: String

                attr_accessor sample: String

                attr_accessor url: String

                attr_accessor variable_type: String

                attr_accessor alt: String?

                attr_accessor regex: String?

                attr_accessor short_url: String?

                def initialize: (
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  ?alt: String?,
                  ?regex: String?,
                  ?short_url: String?
                ) -> void

                def to_hash: -> {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }
              end
            end
          end

          type sms =
            {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable]?
            }

          class SMS < Sentdm::Internal::Type::BaseModel
            attr_accessor template: String

            attr_accessor type: String?

            attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable]?

            def initialize: (
              template: String,
              ?type: String?,
              ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable]?
            ) -> void

            def to_hash: -> {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable]?
            }

            type variable =
              {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable::Props,
                type: String,
                id: Integer
              }

            class Variable < Sentdm::Internal::Type::BaseModel
              attr_accessor name: String

              attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable::Props

              attr_accessor type: String

              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              def initialize: (
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable::Props,
                type: String,
                ?id: Integer
              ) -> void

              def to_hash: -> {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::SMS::Variable::Props,
                type: String,
                id: Integer
              }

              type props =
                {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }

              class Props < Sentdm::Internal::Type::BaseModel
                attr_accessor media_type: String

                attr_accessor sample: String

                attr_accessor url: String

                attr_accessor variable_type: String

                attr_accessor alt: String?

                attr_accessor regex: String?

                attr_accessor short_url: String?

                def initialize: (
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  ?alt: String?,
                  ?regex: String?,
                  ?short_url: String?
                ) -> void

                def to_hash: -> {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }
              end
            end
          end

          type whatsapp =
            {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable]?
            }

          class Whatsapp < Sentdm::Internal::Type::BaseModel
            attr_accessor template: String

            attr_accessor type: String?

            attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable]?

            def initialize: (
              template: String,
              ?type: String?,
              ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable]?
            ) -> void

            def to_hash: -> {
              template: String,
              type: String?,
              variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable]?
            }

            type variable =
              {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable::Props,
                type: String,
                id: Integer
              }

            class Variable < Sentdm::Internal::Type::BaseModel
              attr_accessor name: String

              attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable::Props

              attr_accessor type: String

              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              def initialize: (
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable::Props,
                type: String,
                ?id: Integer
              ) -> void

              def to_hash: -> {
                name: String,
                props: Sentdm::TemplateUpdateParams::Definition::Body::Whatsapp::Variable::Props,
                type: String,
                id: Integer
              }

              type props =
                {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }

              class Props < Sentdm::Internal::Type::BaseModel
                attr_accessor media_type: String

                attr_accessor sample: String

                attr_accessor url: String

                attr_accessor variable_type: String

                attr_accessor alt: String?

                attr_accessor regex: String?

                attr_accessor short_url: String?

                def initialize: (
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  ?alt: String?,
                  ?regex: String?,
                  ?short_url: String?
                ) -> void

                def to_hash: -> {
                  media_type: String,
                  sample: String,
                  url: String,
                  variable_type: String,
                  alt: String?,
                  regex: String?,
                  short_url: String?
                }
              end
            end
          end
        end

        type authentication_config =
          {
            add_security_recommendation: bool,
            code_expiration_minutes: Integer?
          }

        class AuthenticationConfig < Sentdm::Internal::Type::BaseModel
          attr_reader add_security_recommendation: bool?

          def add_security_recommendation=: (bool) -> bool

          attr_accessor code_expiration_minutes: Integer?

          def initialize: (
            ?add_security_recommendation: bool,
            ?code_expiration_minutes: Integer?
          ) -> void

          def to_hash: -> {
            add_security_recommendation: bool,
            code_expiration_minutes: Integer?
          }
        end

        type button =
          {
            props: Sentdm::TemplateUpdateParams::Definition::Button::Props,
            type: String,
            id: Integer
          }

        class Button < Sentdm::Internal::Type::BaseModel
          attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Button::Props

          attr_accessor type: String

          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          def initialize: (
            props: Sentdm::TemplateUpdateParams::Definition::Button::Props,
            type: String,
            ?id: Integer
          ) -> void

          def to_hash: -> {
            props: Sentdm::TemplateUpdateParams::Definition::Button::Props,
            type: String,
            id: Integer
          }

          type props =
            {
              active_for: Integer,
              country_code: String,
              offer_code: String,
              phone_number: String,
              quick_reply_type: String,
              text: String,
              url: String,
              url_type: String,
              autofill_text: String?,
              otp_type: String?,
              package_name: String?,
              signature_hash: String?
            }

          class Props < Sentdm::Internal::Type::BaseModel
            attr_accessor active_for: Integer

            attr_accessor country_code: String

            attr_accessor offer_code: String

            attr_accessor phone_number: String

            attr_accessor quick_reply_type: String

            attr_accessor text: String

            attr_accessor url: String

            attr_accessor url_type: String

            attr_accessor autofill_text: String?

            attr_accessor otp_type: String?

            attr_accessor package_name: String?

            attr_accessor signature_hash: String?

            def initialize: (
              active_for: Integer,
              country_code: String,
              offer_code: String,
              phone_number: String,
              quick_reply_type: String,
              text: String,
              url: String,
              url_type: String,
              ?autofill_text: String?,
              ?otp_type: String?,
              ?package_name: String?,
              ?signature_hash: String?
            ) -> void

            def to_hash: -> {
              active_for: Integer,
              country_code: String,
              offer_code: String,
              phone_number: String,
              quick_reply_type: String,
              text: String,
              url: String,
              url_type: String,
              autofill_text: String?,
              otp_type: String?,
              package_name: String?,
              signature_hash: String?
            }
          end
        end

        type footer =
          {
            template: String,
            type: String?,
            variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Footer::Variable]?
          }

        class Footer < Sentdm::Internal::Type::BaseModel
          attr_accessor template: String

          attr_accessor type: String?

          attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Footer::Variable]?

          def initialize: (
            template: String,
            ?type: String?,
            ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Footer::Variable]?
          ) -> void

          def to_hash: -> {
            template: String,
            type: String?,
            variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Footer::Variable]?
          }

          type variable =
            {
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Footer::Variable::Props,
              type: String,
              id: Integer
            }

          class Variable < Sentdm::Internal::Type::BaseModel
            attr_accessor name: String

            attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Footer::Variable::Props

            attr_accessor type: String

            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            def initialize: (
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Footer::Variable::Props,
              type: String,
              ?id: Integer
            ) -> void

            def to_hash: -> {
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Footer::Variable::Props,
              type: String,
              id: Integer
            }

            type props =
              {
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                alt: String?,
                regex: String?,
                short_url: String?
              }

            class Props < Sentdm::Internal::Type::BaseModel
              attr_accessor media_type: String

              attr_accessor sample: String

              attr_accessor url: String

              attr_accessor variable_type: String

              attr_accessor alt: String?

              attr_accessor regex: String?

              attr_accessor short_url: String?

              def initialize: (
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                ?alt: String?,
                ?regex: String?,
                ?short_url: String?
              ) -> void

              def to_hash: -> {
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                alt: String?,
                regex: String?,
                short_url: String?
              }
            end
          end
        end

        type header =
          {
            template: String,
            type: String?,
            variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Header::Variable]?
          }

        class Header < Sentdm::Internal::Type::BaseModel
          attr_accessor template: String

          attr_accessor type: String?

          attr_accessor variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Header::Variable]?

          def initialize: (
            template: String,
            ?type: String?,
            ?variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Header::Variable]?
          ) -> void

          def to_hash: -> {
            template: String,
            type: String?,
            variables: ::Array[Sentdm::TemplateUpdateParams::Definition::Header::Variable]?
          }

          type variable =
            {
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Header::Variable::Props,
              type: String,
              id: Integer
            }

          class Variable < Sentdm::Internal::Type::BaseModel
            attr_accessor name: String

            attr_accessor props: Sentdm::TemplateUpdateParams::Definition::Header::Variable::Props

            attr_accessor type: String

            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            def initialize: (
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Header::Variable::Props,
              type: String,
              ?id: Integer
            ) -> void

            def to_hash: -> {
              name: String,
              props: Sentdm::TemplateUpdateParams::Definition::Header::Variable::Props,
              type: String,
              id: Integer
            }

            type props =
              {
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                alt: String?,
                regex: String?,
                short_url: String?
              }

            class Props < Sentdm::Internal::Type::BaseModel
              attr_accessor media_type: String

              attr_accessor sample: String

              attr_accessor url: String

              attr_accessor variable_type: String

              attr_accessor alt: String?

              attr_accessor regex: String?

              attr_accessor short_url: String?

              def initialize: (
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                ?alt: String?,
                ?regex: String?,
                ?short_url: String?
              ) -> void

              def to_hash: -> {
                media_type: String,
                sample: String,
                url: String,
                variable_type: String,
                alt: String?,
                regex: String?,
                short_url: String?
              }
            end
          end
        end
      end
    end
  end
end
