module Sentdm
  module Models
    type template_list_params =
      {
        page: Integer,
        page_size: Integer,
        category: String?,
        search: String?,
        status: String?
      }
      & Sentdm::Internal::Type::request_parameters

    class TemplateListParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor page: Integer

      attr_accessor page_size: Integer

      attr_accessor category: String?

      attr_accessor search: String?

      attr_accessor status: String?

      def initialize: (
        page: Integer,
        page_size: Integer,
        ?category: String?,
        ?search: String?,
        ?status: String?,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        page: Integer,
        page_size: Integer,
        category: String?,
        search: String?,
        status: String?,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
