module Sentdm
  module Models
    type template_list_response =
      {
        data: Sentdm::Models::TemplateListResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class TemplateListResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::TemplateListResponse::Data?

      attr_accessor error: Sentdm::APIError?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::TemplateListResponse::Data?,
        ?error: Sentdm::APIError?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::TemplateListResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

      type data =
        {
          pagination: Sentdm::PaginationMeta,
          templates: ::Array[Sentdm::Template]
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader pagination: Sentdm::PaginationMeta?

        def pagination=: (Sentdm::PaginationMeta) -> Sentdm::PaginationMeta

        attr_reader templates: ::Array[Sentdm::Template]?

        def templates=: (::Array[Sentdm::Template]) -> ::Array[Sentdm::Template]

        def initialize: (
          ?pagination: Sentdm::PaginationMeta,
          ?templates: ::Array[Sentdm::Template]
        ) -> void

        def to_hash: -> {
          pagination: Sentdm::PaginationMeta,
          templates: ::Array[Sentdm::Template]
        }
      end
    end
  end
end
