module Sentdm
  module Models
    type user_response =
      {
        id: String,
        created_at: Time,
        email: String,
        invited_at: Time?,
        last_login_at: Time?,
        name: String,
        role: String,
        status: String,
        updated_at: Time?
      }

    class UserResponse < Sentdm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader email: String?

      def email=: (String) -> String

      attr_accessor invited_at: Time?

      attr_accessor last_login_at: Time?

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader role: String?

      def role=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_accessor updated_at: Time?

      def initialize: (
        ?id: String,
        ?created_at: Time,
        ?email: String,
        ?invited_at: Time?,
        ?last_login_at: Time?,
        ?name: String,
        ?role: String,
        ?status: String,
        ?updated_at: Time?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        email: String,
        invited_at: Time?,
        last_login_at: Time?,
        name: String,
        role: String,
        status: String,
        updated_at: Time?
      }
    end
  end
end
