module Sentdm
  module Models
    type webhook_list_events_response =
      {
        id: String,
        created_at: Time,
        delivery_attempts: Integer,
        delivery_status: String,
        error_message: String?,
        event_data: Sentdm::Models::WebhookListEventsResponse::event_data,
        event_type: String,
        http_status_code: Integer?,
        processing_completed_at: Time?,
        processing_started_at: Time?,
        response_body: String?
      }

    class WebhookListEventsResponse < Sentdm::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader delivery_attempts: Integer?

      def delivery_attempts=: (Integer) -> Integer

      attr_reader delivery_status: String?

      def delivery_status=: (String) -> String

      attr_accessor error_message: String?

      attr_reader event_data: Sentdm::Models::WebhookListEventsResponse::event_data?

      def event_data=: (
        Sentdm::Models::WebhookListEventsResponse::event_data
      ) -> Sentdm::Models::WebhookListEventsResponse::event_data

      attr_reader event_type: String?

      def event_type=: (String) -> String

      attr_accessor http_status_code: Integer?

      attr_accessor processing_completed_at: Time?

      attr_accessor processing_started_at: Time?

      attr_accessor response_body: String?

      def initialize: (
        ?id: String,
        ?created_at: Time,
        ?delivery_attempts: Integer,
        ?delivery_status: String,
        ?error_message: String?,
        ?event_data: Sentdm::Models::WebhookListEventsResponse::event_data,
        ?event_type: String,
        ?http_status_code: Integer?,
        ?processing_completed_at: Time?,
        ?processing_started_at: Time?,
        ?response_body: String?
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        delivery_attempts: Integer,
        delivery_status: String,
        error_message: String?,
        event_data: Sentdm::Models::WebhookListEventsResponse::event_data,
        event_type: String,
        http_status_code: Integer?,
        processing_completed_at: Time?,
        processing_started_at: Time?,
        response_body: String?
      }

      type event_data =
        Sentdm::MessageEvent
        | Sentdm::InboundMessageEvent
        | Sentdm::TemplateEvent
        | Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload
        | Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload

      module EventData
        extend Sentdm::Internal::Type::Union

        type sent_dm_services_common_services_webhooks_contracts_webhook_event_of_channel_webhook_payload =
          {
            event: String?,
            field: String,
            payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload::Payload?,
            request_id: String?,
            timestamp: String
          }

        class SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload < Sentdm::Internal::Type::BaseModel
          attr_accessor event: String?

          attr_reader field: String?

          def field=: (String) -> String

          attr_accessor payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload::Payload?

          attr_accessor request_id: String?

          attr_reader timestamp: String?

          def timestamp=: (String) -> String

          def initialize: (
            ?event: String?,
            ?field: String,
            ?payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload::Payload?,
            ?request_id: String?,
            ?timestamp: String
          ) -> void

          def to_hash: -> {
            event: String?,
            field: String,
            payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfChannelWebhookPayload::Payload?,
            request_id: String?,
            timestamp: String
          }

          type payload =
            {
              country: String,
              account_id: String,
              channel: String,
              number_type: String?,
              reason: String?,
              sender_value: String?,
              status: String,
              updated_at: String
            }

          class Payload < Sentdm::Internal::Type::BaseModel
            attr_accessor country: String

            attr_reader account_id: String?

            def account_id=: (String) -> String

            attr_reader channel: String?

            def channel=: (String) -> String

            attr_accessor number_type: String?

            attr_accessor reason: String?

            attr_accessor sender_value: String?

            attr_reader status: String?

            def status=: (String) -> String

            attr_reader updated_at: String?

            def updated_at=: (String) -> String

            def initialize: (
              country: String,
              ?account_id: String,
              ?channel: String,
              ?number_type: String?,
              ?reason: String?,
              ?sender_value: String?,
              ?status: String,
              ?updated_at: String
            ) -> void

            def to_hash: -> {
              country: String,
              account_id: String,
              channel: String,
              number_type: String?,
              reason: String?,
              sender_value: String?,
              status: String,
              updated_at: String
            }
          end
        end

        type sent_dm_services_common_services_webhooks_contracts_webhook_event_of_contact_webhook_payload =
          {
            event: String?,
            field: String,
            payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload::Payload?,
            request_id: String?,
            timestamp: String
          }

        class SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload < Sentdm::Internal::Type::BaseModel
          attr_accessor event: String?

          attr_reader field: String?

          def field=: (String) -> String

          attr_accessor payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload::Payload?

          attr_accessor request_id: String?

          attr_reader timestamp: String?

          def timestamp=: (String) -> String

          def initialize: (
            ?event: String?,
            ?field: String,
            ?payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload::Payload?,
            ?request_id: String?,
            ?timestamp: String
          ) -> void

          def to_hash: -> {
            event: String?,
            field: String,
            payload: Sentdm::Models::WebhookListEventsResponse::EventData::SentDmServicesCommonServicesWebhooksContractsWebhookEventOfContactWebhookPayload::Payload?,
            request_id: String?,
            timestamp: String
          }

          type payload =
            {
              opt_out: bool,
              source: String,
              account_id: String,
              channel: String,
              contact_id: String,
              message_id: String?,
              phone_number: String,
              text: String?
            }

          class Payload < Sentdm::Internal::Type::BaseModel
            attr_accessor opt_out: bool

            attr_accessor source: String

            attr_reader account_id: String?

            def account_id=: (String) -> String

            attr_reader channel: String?

            def channel=: (String) -> String

            attr_reader contact_id: String?

            def contact_id=: (String) -> String

            attr_accessor message_id: String?

            attr_reader phone_number: String?

            def phone_number=: (String) -> String

            attr_accessor text: String?

            def initialize: (
              opt_out: bool,
              source: String,
              ?account_id: String,
              ?channel: String,
              ?contact_id: String,
              ?message_id: String?,
              ?phone_number: String,
              ?text: String?
            ) -> void

            def to_hash: -> {
              opt_out: bool,
              source: String,
              account_id: String,
              channel: String,
              contact_id: String,
              message_id: String?,
              phone_number: String,
              text: String?
            }
          end
        end

        def self?.variants: -> ::Array[Sentdm::Models::WebhookListEventsResponse::event_data]
      end
    end
  end
end
