module Sentdm
  module Models
    type webhook_update_params =
      {
        id: String,
        display_name: String,
        endpoint_url: String,
        event_filters: ::Hash[Symbol, ::Array[String]]?,
        event_types: ::Array[String],
        retry_count: Integer,
        sandbox: bool,
        timeout_seconds: Integer,
        idempotency_key: String,
        x_profile_id: String
      }
      & Sentdm::Internal::Type::request_parameters

    class WebhookUpdateParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader endpoint_url: String?

      def endpoint_url=: (String) -> String

      attr_accessor event_filters: ::Hash[Symbol, ::Array[String]]?

      attr_reader event_types: ::Array[String]?

      def event_types=: (::Array[String]) -> ::Array[String]

      attr_reader retry_count: Integer?

      def retry_count=: (Integer) -> Integer

      attr_reader sandbox: bool?

      def sandbox=: (bool) -> bool

      attr_reader timeout_seconds: Integer?

      def timeout_seconds=: (Integer) -> Integer

      attr_reader idempotency_key: String?

      def idempotency_key=: (String) -> String

      attr_reader x_profile_id: String?

      def x_profile_id=: (String) -> String

      def initialize: (
        id: String,
        ?display_name: String,
        ?endpoint_url: String,
        ?event_filters: ::Hash[Symbol, ::Array[String]]?,
        ?event_types: ::Array[String],
        ?retry_count: Integer,
        ?sandbox: bool,
        ?timeout_seconds: Integer,
        ?idempotency_key: String,
        ?x_profile_id: String,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        display_name: String,
        endpoint_url: String,
        event_filters: ::Hash[Symbol, ::Array[String]]?,
        event_types: ::Array[String],
        retry_count: Integer,
        sandbox: bool,
        timeout_seconds: Integer,
        idempotency_key: String,
        x_profile_id: String,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
