module Sentdm
  module Models
    type webhook_list_params =
      { page: Integer, page_size: Integer, is_active: bool?, search: String? }
      & Sentdm::Internal::Type::request_parameters

    class WebhookListParams < Sentdm::Internal::Type::BaseModel
      extend Sentdm::Internal::Type::RequestParameters::Converter
      include Sentdm::Internal::Type::RequestParameters

      attr_accessor page: Integer

      attr_accessor page_size: Integer

      attr_accessor is_active: bool?

      attr_accessor search: String?

      def initialize: (
        page: Integer,
        page_size: Integer,
        ?is_active: bool?,
        ?search: String?,
        ?request_options: Sentdm::request_opts
      ) -> void

      def to_hash: -> {
        page: Integer,
        page_size: Integer,
        is_active: bool?,
        search: String?,
        request_options: Sentdm::RequestOptions
      }
    end
  end
end
