module Sentdm
  module Models
    type webhook_list_event_types_response =
      {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::Models::WebhookListEventTypesResponse::Error?,
        meta: Sentdm::Models::WebhookListEventTypesResponse::Meta,
        success: bool
      }

    class WebhookListEventTypesResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::WebhookListEventTypesResponse::Data?

      attr_accessor error: Sentdm::Models::WebhookListEventTypesResponse::Error?

      attr_reader meta: Sentdm::Models::WebhookListEventTypesResponse::Meta?

      def meta=: (
        Sentdm::Models::WebhookListEventTypesResponse::Meta
      ) -> Sentdm::Models::WebhookListEventTypesResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        ?error: Sentdm::Models::WebhookListEventTypesResponse::Error?,
        ?meta: Sentdm::Models::WebhookListEventTypesResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::Models::WebhookListEventTypesResponse::Error?,
        meta: Sentdm::Models::WebhookListEventTypesResponse::Meta,
        success: bool
      }

      type data =
        {
          event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType],
          pagination: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]?

        def event_types=: (
          ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]
        ) -> ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]

        attr_reader pagination: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination?

        def pagination=: (
          Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination
        ) -> Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination

        def initialize: (
          ?event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType],
          ?pagination: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination
        ) -> void

        def to_hash: -> {
          event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType],
          pagination: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination
        }

        type event_type =
          {
            description: String?,
            display_name: String,
            event_type: String?,
            is_active: bool,
            name: String,
            sub_types: ::Array[top]?
          }

        class EventType < Sentdm::Internal::Type::BaseModel
          attr_accessor description: String?

          attr_reader display_name: String?

          def display_name=: (String) -> String

          attr_accessor event_type: String?

          attr_reader is_active: bool?

          def is_active=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_accessor sub_types: ::Array[top]?

          def initialize: (
            ?description: String?,
            ?display_name: String,
            ?event_type: String?,
            ?is_active: bool,
            ?name: String,
            ?sub_types: ::Array[top]?
          ) -> void

          def to_hash: -> {
            description: String?,
            display_name: String,
            event_type: String?,
            is_active: bool,
            name: String,
            sub_types: ::Array[top]?
          }
        end

        type pagination =
          {
            cursors: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination::Cursors?,
            has_more: bool,
            page: Integer,
            page_size: Integer,
            total_count: Integer,
            total_pages: Integer
          }

        class Pagination < Sentdm::Internal::Type::BaseModel
          attr_accessor cursors: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination::Cursors?

          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          attr_reader page: Integer?

          def page=: (Integer) -> Integer

          attr_reader page_size: Integer?

          def page_size=: (Integer) -> Integer

          attr_reader total_count: Integer?

          def total_count=: (Integer) -> Integer

          attr_reader total_pages: Integer?

          def total_pages=: (Integer) -> Integer

          def initialize: (
            ?cursors: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination::Cursors?,
            ?has_more: bool,
            ?page: Integer,
            ?page_size: Integer,
            ?total_count: Integer,
            ?total_pages: Integer
          ) -> void

          def to_hash: -> {
            cursors: Sentdm::Models::WebhookListEventTypesResponse::Data::Pagination::Cursors?,
            has_more: bool,
            page: Integer,
            page_size: Integer,
            total_count: Integer,
            total_pages: Integer
          }

          type cursors = { after: String?, before: String? }

          class Cursors < Sentdm::Internal::Type::BaseModel
            attr_accessor after: String?

            attr_accessor before: String?

            def initialize: (?after: String?, ?before: String?) -> void

            def to_hash: -> { after: String?, before: String? }
          end
        end
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
