module Sentdm
  module Models
    type webhook_test_response =
      {
        data: Sentdm::Models::WebhookTestResponse::Data?,
        error: Sentdm::Models::WebhookTestResponse::Error?,
        meta: Sentdm::Models::WebhookTestResponse::Meta,
        success: bool
      }

    class WebhookTestResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::WebhookTestResponse::Data?

      attr_accessor error: Sentdm::Models::WebhookTestResponse::Error?

      attr_reader meta: Sentdm::Models::WebhookTestResponse::Meta?

      def meta=: (
        Sentdm::Models::WebhookTestResponse::Meta
      ) -> Sentdm::Models::WebhookTestResponse::Meta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::WebhookTestResponse::Data?,
        ?error: Sentdm::Models::WebhookTestResponse::Error?,
        ?meta: Sentdm::Models::WebhookTestResponse::Meta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::WebhookTestResponse::Data?,
        error: Sentdm::Models::WebhookTestResponse::Error?,
        meta: Sentdm::Models::WebhookTestResponse::Meta,
        success: bool
      }

      type data = { message: String, success: bool }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader message: String?

        def message=: (String) -> String

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (?message: String, ?success: bool) -> void

        def to_hash: -> { message: String, success: bool }
      end

      type error =
        {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }

      class Error < Sentdm::Internal::Type::BaseModel
        attr_reader code: String?

        def code=: (String) -> String

        attr_accessor details: ::Hash[Symbol, ::Array[String]]?

        attr_accessor doc_url: String?

        attr_reader message: String?

        def message=: (String) -> String

        def initialize: (
          ?code: String,
          ?details: ::Hash[Symbol, ::Array[String]]?,
          ?doc_url: String?,
          ?message: String
        ) -> void

        def to_hash: -> {
          code: String,
          details: ::Hash[Symbol, ::Array[String]]?,
          doc_url: String?,
          message: String
        }
      end

      type meta = { request_id: String, timestamp: Time, version: String }

      class Meta < Sentdm::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        attr_reader version: String?

        def version=: (String) -> String

        def initialize: (
          ?request_id: String,
          ?timestamp: Time,
          ?version: String
        ) -> void

        def to_hash: -> { request_id: String, timestamp: Time, version: String }
      end
    end
  end
end
