module Sentdm
  module Models
    type webhook_list_event_types_response =
      {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::ErrorDetail?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class WebhookListEventTypesResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::WebhookListEventTypesResponse::Data?

      attr_accessor error: Sentdm::ErrorDetail?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        ?error: Sentdm::ErrorDetail?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::ErrorDetail?,
        meta: Sentdm::APIMeta,
        success: bool
      }

      type data = { event_types: ::Array[Sentdm::WebhookEventType] }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader event_types: ::Array[Sentdm::WebhookEventType]?

        def event_types=: (
          ::Array[Sentdm::WebhookEventType]
        ) -> ::Array[Sentdm::WebhookEventType]

        def initialize: (
          ?event_types: ::Array[Sentdm::WebhookEventType]
        ) -> void

        def to_hash: -> { event_types: ::Array[Sentdm::WebhookEventType] }
      end
    end
  end
end
