module Sentdm
  module Models
    type webhook_rotate_secret_response =
      {
        data: Sentdm::Models::WebhookRotateSecretResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class WebhookRotateSecretResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::WebhookRotateSecretResponse::Data?

      attr_accessor error: Sentdm::APIError?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::WebhookRotateSecretResponse::Data?,
        ?error: Sentdm::APIError?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::WebhookRotateSecretResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

      type data = { signing_secret: String }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader signing_secret: String?

        def signing_secret=: (String) -> String

        def initialize: (?signing_secret: String) -> void

        def to_hash: -> { signing_secret: String }
      end
    end
  end
end
