module Sentdm
  module Models
    type webhook_list_event_types_response =
      {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

    class WebhookListEventTypesResponse < Sentdm::Internal::Type::BaseModel
      attr_accessor data: Sentdm::Models::WebhookListEventTypesResponse::Data?

      attr_accessor error: Sentdm::APIError?

      attr_reader meta: Sentdm::APIMeta?

      def meta=: (Sentdm::APIMeta) -> Sentdm::APIMeta

      attr_reader success: bool?

      def success=: (bool) -> bool

      def initialize: (
        ?data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        ?error: Sentdm::APIError?,
        ?meta: Sentdm::APIMeta,
        ?success: bool
      ) -> void

      def to_hash: -> {
        data: Sentdm::Models::WebhookListEventTypesResponse::Data?,
        error: Sentdm::APIError?,
        meta: Sentdm::APIMeta,
        success: bool
      }

      type data =
        {
          event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]
        }

      class Data < Sentdm::Internal::Type::BaseModel
        attr_reader event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]?

        def event_types=: (
          ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]
        ) -> ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]

        def initialize: (
          ?event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]
        ) -> void

        def to_hash: -> {
          event_types: ::Array[Sentdm::Models::WebhookListEventTypesResponse::Data::EventType]
        }

        type event_type =
          {
            description: String?,
            display_name: String,
            is_active: bool,
            name: String
          }

        class EventType < Sentdm::Internal::Type::BaseModel
          attr_accessor description: String?

          attr_reader display_name: String?

          def display_name=: (String) -> String

          attr_reader is_active: bool?

          def is_active=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          def initialize: (
            ?description: String?,
            ?display_name: String,
            ?is_active: bool,
            ?name: String
          ) -> void

          def to_hash: -> {
            description: String?,
            display_name: String,
            is_active: bool,
            name: String
          }
        end
      end
    end
  end
end
