module Sentdm
  class AuthenticationConfig = Sentdm::Models::AuthenticationConfig

  class ContactCreateParams = Sentdm::Models::ContactCreateParams

  class ContactDeleteParams = Sentdm::Models::ContactDeleteParams

  class ContactListParams = Sentdm::Models::ContactListParams

  class ContactRetrieveMessageSummaryParams = Sentdm::Models::ContactRetrieveMessageSummaryParams

  class ContactRetrieveParams = Sentdm::Models::ContactRetrieveParams

  class ContactUpdateParams = Sentdm::Models::ContactUpdateParams

  class ConversationListMessagesParams = Sentdm::Models::ConversationListMessagesParams

  class ConversationListParams = Sentdm::Models::ConversationListParams

  class DestinationCountry = Sentdm::Models::DestinationCountry

  class InboundMessageEvent = Sentdm::Models::InboundMessageEvent

  class InboundMessageEventPayload = Sentdm::Models::InboundMessageEventPayload

  class MeRetrieveParams = Sentdm::Models::MeRetrieveParams

  class MessageEvent = Sentdm::Models::MessageEvent

  class MessageEventPayload = Sentdm::Models::MessageEventPayload

  class MessageRetrieveActivitiesParams = Sentdm::Models::MessageRetrieveActivitiesParams

  class MessageRetrieveStatusParams = Sentdm::Models::MessageRetrieveStatusParams

  class MessageSendParams = Sentdm::Models::MessageSendParams

  class NumberLookupParams = Sentdm::Models::NumberLookupParams

  class ProfileCompleteParams = Sentdm::Models::ProfileCompleteParams

  class ProfileCreateParams = Sentdm::Models::ProfileCreateParams

  class ProfileDeleteParams = Sentdm::Models::ProfileDeleteParams

  class ProfileListParams = Sentdm::Models::ProfileListParams

  class ProfileRetrieveParams = Sentdm::Models::ProfileRetrieveParams

  module Profiles = Sentdm::Models::Profiles

  class ProfileUpdateParams = Sentdm::Models::ProfileUpdateParams

  module TcrBrandRelationship = Sentdm::Models::TcrBrandRelationship

  module TcrVertical = Sentdm::Models::TcrVertical

  class TemplateBody = Sentdm::Models::TemplateBody

  class TemplateBodyContent = Sentdm::Models::TemplateBodyContent

  class TemplateButton = Sentdm::Models::TemplateButton

  class TemplateButtonProps = Sentdm::Models::TemplateButtonProps

  class TemplateCreateParams = Sentdm::Models::TemplateCreateParams

  class TemplateDefinition = Sentdm::Models::TemplateDefinition

  class TemplateDeleteParams = Sentdm::Models::TemplateDeleteParams

  class TemplateEvent = Sentdm::Models::TemplateEvent

  class TemplateEventPayload = Sentdm::Models::TemplateEventPayload

  class TemplateFooter = Sentdm::Models::TemplateFooter

  class TemplateHeader = Sentdm::Models::TemplateHeader

  class TemplateListParams = Sentdm::Models::TemplateListParams

  class TemplateRetrieveParams = Sentdm::Models::TemplateRetrieveParams

  class TemplateUpdateParams = Sentdm::Models::TemplateUpdateParams

  class TemplateVariable = Sentdm::Models::TemplateVariable

  class UserInviteParams = Sentdm::Models::UserInviteParams

  class UserListParams = Sentdm::Models::UserListParams

  class UserRemoveParams = Sentdm::Models::UserRemoveParams

  class UserRetrieveParams = Sentdm::Models::UserRetrieveParams

  class UserUpdateRoleParams = Sentdm::Models::UserUpdateRoleParams

  class WebhookCreateParams = Sentdm::Models::WebhookCreateParams

  class WebhookDeleteParams = Sentdm::Models::WebhookDeleteParams

  class WebhookListEventsParams = Sentdm::Models::WebhookListEventsParams

  class WebhookListEventTypesParams = Sentdm::Models::WebhookListEventTypesParams

  class WebhookListParams = Sentdm::Models::WebhookListParams

  class WebhookRetrieveParams = Sentdm::Models::WebhookRetrieveParams

  class WebhookRotateSecretParams = Sentdm::Models::WebhookRotateSecretParams

  class WebhookTestParams = Sentdm::Models::WebhookTestParams

  class WebhookToggleStatusParams = Sentdm::Models::WebhookToggleStatusParams

  class WebhookUpdateParams = Sentdm::Models::WebhookUpdateParams
end
