module Sentdm
  class ContactCreateParams = Sentdm::Models::ContactCreateParams

  class ContactDeleteParams = Sentdm::Models::ContactDeleteParams

  class ContactListParams = Sentdm::Models::ContactListParams

  class ContactRetrieveParams = Sentdm::Models::ContactRetrieveParams

  class ContactUpdateParams = Sentdm::Models::ContactUpdateParams

  class MeRetrieveParams = Sentdm::Models::MeRetrieveParams

  class MessageRetrieveActivitiesParams = Sentdm::Models::MessageRetrieveActivitiesParams

  class MessageRetrieveStatusParams = Sentdm::Models::MessageRetrieveStatusParams

  class MessageSendParams = Sentdm::Models::MessageSendParams

  class NumberLookupParams = Sentdm::Models::NumberLookupParams

  class ProfileCompleteParams = Sentdm::Models::ProfileCompleteParams

  class ProfileCreateParams = Sentdm::Models::ProfileCreateParams

  class ProfileDeleteParams = Sentdm::Models::ProfileDeleteParams

  class ProfileListParams = Sentdm::Models::ProfileListParams

  class ProfileRetrieveParams = Sentdm::Models::ProfileRetrieveParams

  module Profiles = Sentdm::Models::Profiles

  class ProfileUpdateParams = Sentdm::Models::ProfileUpdateParams

  class TemplateCreateParams = Sentdm::Models::TemplateCreateParams

  class TemplateDeleteParams = Sentdm::Models::TemplateDeleteParams

  class TemplateListParams = Sentdm::Models::TemplateListParams

  class TemplateRetrieveParams = Sentdm::Models::TemplateRetrieveParams

  class TemplateUpdateParams = Sentdm::Models::TemplateUpdateParams

  class UserInviteParams = Sentdm::Models::UserInviteParams

  class UserListParams = Sentdm::Models::UserListParams

  class UserRemoveParams = Sentdm::Models::UserRemoveParams

  class UserRetrieveParams = Sentdm::Models::UserRetrieveParams

  class UserUpdateRoleParams = Sentdm::Models::UserUpdateRoleParams

  class WebhookCreateParams = Sentdm::Models::WebhookCreateParams

  class WebhookDeleteParams = Sentdm::Models::WebhookDeleteParams

  class WebhookListEventsParams = Sentdm::Models::WebhookListEventsParams

  class WebhookListEventTypesParams = Sentdm::Models::WebhookListEventTypesParams

  class WebhookListParams = Sentdm::Models::WebhookListParams

  class WebhookRetrieveParams = Sentdm::Models::WebhookRetrieveParams

  class WebhookRotateSecretParams = Sentdm::Models::WebhookRotateSecretParams

  class WebhookTestParams = Sentdm::Models::WebhookTestParams

  class WebhookToggleStatusParams = Sentdm::Models::WebhookToggleStatusParams

  class WebhookUpdateParams = Sentdm::Models::WebhookUpdateParams
end
