module Sentdm
  class ContactListItem = Sentdm::Models::ContactListItem

  class ContactListParams = Sentdm::Models::ContactListParams

  class ContactRetrieveByPhoneParams = Sentdm::Models::ContactRetrieveByPhoneParams

  class ContactRetrieveIDParams = Sentdm::Models::ContactRetrieveIDParams

  class MessageRetrieveParams = Sentdm::Models::MessageRetrieveParams

  class MessageSendQuickMessageParams = Sentdm::Models::MessageSendQuickMessageParams

  class MessageSendToContactParams = Sentdm::Models::MessageSendToContactParams

  class MessageSendToPhoneParams = Sentdm::Models::MessageSendToPhoneParams

  class NumberLookupRetrieveParams = Sentdm::Models::NumberLookupRetrieveParams

  class TemplateBodyContent = Sentdm::Models::TemplateBodyContent

  class TemplateCreateParams = Sentdm::Models::TemplateCreateParams

  class TemplateDefinition = Sentdm::Models::TemplateDefinition

  class TemplateDeleteParams = Sentdm::Models::TemplateDeleteParams

  class TemplateListParams = Sentdm::Models::TemplateListParams

  class TemplateResponseV2 = Sentdm::Models::TemplateResponseV2

  class TemplateRetrieveParams = Sentdm::Models::TemplateRetrieveParams

  class TemplateVariable = Sentdm::Models::TemplateVariable
end
