module SentDm
  module Resources
    class Brands
      class Campaigns
        def create: (
          String brand_id,
          campaign: SentDm::Brands::CampaignData,
          ?test_mode: bool,
          ?idempotency_key: String,
          ?request_options: SentDm::request_opts
        ) -> SentDm::Brands::APIResponseTcrCampaignWithUseCases

        def update: (
          String campaign_id,
          brand_id: String,
          campaign: SentDm::Brands::CampaignData,
          ?test_mode: bool,
          ?idempotency_key: String,
          ?request_options: SentDm::request_opts
        ) -> SentDm::Brands::APIResponseTcrCampaignWithUseCases

        def list: (
          String brand_id,
          ?request_options: SentDm::request_opts
        ) -> SentDm::Models::Brands::CampaignListResponse

        def delete: (
          String campaign_id,
          brand_id: String,
          body: SentDm::Brands::CampaignDeleteParams::Body,
          ?request_options: SentDm::request_opts
        ) -> nil

        def initialize: (client: SentDm::Client) -> void
      end
    end
  end
end
