module SentDm
  module Models
    module Organizations
      type user_update_role_params =
        { customer_id: String, role: String }
        & SentDm::Internal::Type::request_parameters

      class UserUpdateRoleParams < SentDm::Internal::Type::BaseModel
        extend SentDm::Internal::Type::RequestParameters::Converter
        include SentDm::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        attr_reader role: String?

        def role=: (String) -> String

        def initialize: (
          customer_id: String,
          ?role: String,
          ?request_options: SentDm::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          role: String,
          request_options: SentDm::RequestOptions
        }
      end
    end
  end
end
