module SentDm
  module Models
    module Organizations
      type user_delete_params =
        { customer_id: String } & SentDm::Internal::Type::request_parameters

      class UserDeleteParams < SentDm::Internal::Type::BaseModel
        extend SentDm::Internal::Type::RequestParameters::Converter
        include SentDm::Internal::Type::RequestParameters

        attr_accessor customer_id: String

        def initialize: (
          customer_id: String,
          ?request_options: SentDm::request_opts
        ) -> void

        def to_hash: -> {
          customer_id: String,
          request_options: SentDm::RequestOptions
        }
      end
    end
  end
end
